export interface NutritionMacros {
  fat: string;
  carbs: string;
  protein: string;
}

export interface Product {
  id: string;
  label: string;
  name: string;
  size: string;
  price: number;
  category: 'produce' | 'dairy-alt' | 'bakery' | 'juice-bar' | 'pantry' | 'sweet-treats' | 'deli';
  description: string;
  image: string;
  origin: {
    region: string;
    altitude: string;
    harvest: string;
  };
  macros: NutritionMacros;
  pairingIds: string[];
  logistics: {
    freshness: string;
    packaging: string;
    carbon: string;
  };
}

export const products: Product[] = [
  // ─── THE GARDEN / PRODUCE (10) ────────────────────────────────
  {
    id: 'organic-kale',
    label: 'ORGANIC',
    name: 'Organic Kale',
    size: '1 BUNCH',
    price: 3.50,
    category: 'produce',
    description: 'Hand-picked lacinato kale with deep pigment and structural integrity.',
    image: '/assets/garden1.webp',
    origin: { region: 'Salinas Valley, CA', altitude: 'Coastal lowland, cool marine fog', harvest: 'Hand-cut at dawn for maximum turgor' },
    macros: { fat: '0.5g', carbs: '6g', protein: '3g' },
    pairingIds: ['olive-oil', 'meyer-lemon', 'sea-salt'],
    logistics: { freshness: '3–5 days from harvest', packaging: 'Compostable band wrap', carbon: '0.3kg CO₂e per unit' },
  },
  {
    id: 'heirloom-tomato',
    label: 'HEIRLOOM',
    name: 'Heirloom Tomato',
    size: '1 LB',
    price: 4.00,
    category: 'produce',
    description: 'Heritage seeds providing a complex balance of acidity and natural sugars.',
    image: '/assets/garden2.webp',
    origin: { region: 'Central Coast, CA', altitude: 'Mediterranean climate, dry-farmed', harvest: 'Vine-ripened, hand-selected' },
    macros: { fat: '0.2g', carbs: '4g', protein: '1g' },
    pairingIds: ['sea-salt', 'olive-oil', 'fresh-mint'],
    logistics: { freshness: '4–6 days from harvest', packaging: 'Recycled pulp tray', carbon: '0.4kg CO₂e per unit' },
  },
  {
    id: 'hass-avocado',
    label: 'ORGANIC',
    name: 'Hass Avocado',
    size: 'EACH',
    price: 2.50,
    category: 'produce',
    description: 'Buttery, high-fat content avocado sourced from volcanic soil regions.',
    image: '/assets/garden3.webp',
    origin: { region: 'Michoacán, Mexico', altitude: '2,200m elevation, volcanic soil', harvest: 'Hand-picked at peak ripeness' },
    macros: { fat: '15g', carbs: '9g', protein: '2g' },
    pairingIds: ['sea-salt', 'meyer-lemon', 'sourdough-boule'],
    logistics: { freshness: '5–7 days from harvest', packaging: 'Recycled kraft tray', carbon: '0.8kg CO₂e per unit' },
  },
  {
    id: 'pink-lady-apple',
    label: 'CONVENTIONAL',
    name: 'Pink Lady Apple',
    size: 'EACH',
    price: 1.50,
    category: 'produce',
    description: 'Crunchy, sweet-tart profile with a vibrant pink blush.',
    image: '/assets/garden4.webp',
    origin: { region: 'Yakima Valley, WA', altitude: 'Temperate orchard, full sun exposure', harvest: 'Late-season harvest for maximum sweetness' },
    macros: { fat: '0.2g', carbs: '25g', protein: '0.5g' },
    pairingIds: ['raw-honey', 'almond-croissant'],
    logistics: { freshness: '2–3 weeks cold storage', packaging: 'Loose, no packaging', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'blueberry',
    label: 'WILD',
    name: 'Blueberry',
    size: '6 OZ',
    price: 5.00,
    category: 'produce',
    description: 'Antioxidant-rich wild varieties with a deep, concentrated flavor.',
    image: '/assets/garden5.webp',
    origin: { region: 'Maine, USA', altitude: 'Wild lowbush, acidic barrens', harvest: 'Hand-raked at peak ripeness' },
    macros: { fat: '0.3g', carbs: '14g', protein: '0.7g' },
    pairingIds: ['cashew-yogurt', 'raw-honey'],
    logistics: { freshness: '5–7 days from harvest', packaging: 'Compostable clamshell', carbon: '0.3kg CO₂e per unit' },
  },
  {
    id: 'meyer-lemon',
    label: 'ORGANIC',
    name: 'Meyer Lemon',
    size: 'EACH',
    price: 1.25,
    category: 'produce',
    description: 'A cross between a citron and a mandarin, known for its herbal sweetness.',
    image: '/assets/garden6.webp',
    origin: { region: 'Ojai, CA', altitude: 'Coastal valley, subtropical microclimate', harvest: 'Tree-ripened, hand-picked' },
    macros: { fat: '0.3g', carbs: '9g', protein: '1g' },
    pairingIds: ['raw-honey', 'earl-grey-tea', 'vitality-juice'],
    logistics: { freshness: '7–10 days from harvest', packaging: 'Loose, no packaging', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'fresh-mint',
    label: 'ORGANIC',
    name: 'Fresh Mint',
    size: '1 BUNCH',
    price: 2.00,
    category: 'produce',
    description: 'Aromatic and cooling leaves, perfect for tonics or infusions.',
    image: '/assets/garden7.webp',
    origin: { region: 'Hudson Valley, NY', altitude: 'River valley, rich alluvial soil', harvest: 'Cut-to-order for peak oil content' },
    macros: { fat: '0.1g', carbs: '1g', protein: '0.4g' },
    pairingIds: ['meyer-lemon', 'matcha-tonic'],
    logistics: { freshness: '3–5 days from harvest', packaging: 'Compostable band wrap', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'english-cucumber',
    label: 'HOTHOUSE',
    name: 'English Cucumber',
    size: 'EACH',
    price: 2.00,
    category: 'produce',
    description: 'Seedless and thin-skinned for a refreshing, high-hydration crunch.',
    image: '/assets/garden8.webp',
    origin: { region: 'British Columbia, Canada', altitude: 'Controlled environment, hydroponic', harvest: 'Daily harvest at optimal length' },
    macros: { fat: '0.1g', carbs: '4g', protein: '0.7g' },
    pairingIds: ['sea-salt', 'fresh-mint'],
    logistics: { freshness: '7–10 days', packaging: 'Shrink-wrapped for freshness', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'rainbow-carrot',
    label: 'HERITAGE',
    name: 'Rainbow Carrot',
    size: '1 LB',
    price: 4.50,
    category: 'produce',
    description: 'Multi-colored heritage carrots providing a spectrum of earthiness.',
    image: '/assets/garden9.webp',
    origin: { region: 'Skagit Valley, WA', altitude: 'Glacial river delta, mineral-rich loam', harvest: 'Hand-pulled, soil-on for freshness' },
    macros: { fat: '0.2g', carbs: '10g', protein: '0.9g' },
    pairingIds: ['olive-oil', 'raw-honey', 'sea-salt'],
    logistics: { freshness: '10–14 days cold storage', packaging: 'Recycled kraft bag', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'arugula',
    label: 'WILD',
    name: 'Arugula',
    size: '5 OZ',
    price: 4.00,
    category: 'produce',
    description: 'Peppery, wild-harvested greens with a sharp, sophisticated profile.',
    image: '/assets/garden10.webp',
    origin: { region: 'Tuscany, Italy', altitude: 'Sun-drenched hillside terraces', harvest: 'Young leaf harvest for peak spice' },
    macros: { fat: '0.3g', carbs: '2g', protein: '2.6g' },
    pairingIds: ['olive-oil', 'balsamic', 'prosciutto'],
    logistics: { freshness: '3–5 days from harvest', packaging: 'Compostable clamshell', carbon: '0.4kg CO₂e per unit' },
  },

  // ─── THE BAKERY (11) ─────────────────────────────────────────
  {
    id: 'sourdough-boule',
    label: 'ARTISAN',
    name: 'Sourdough Boule',
    size: '1 LOAF',
    price: 9.00,
    category: 'bakery',
    description: 'Fermented for 24 hours for a perfect tang and scorched crust.',
    image: '/assets/bakery1.webp',
    origin: { region: 'In-house Bakery', altitude: 'Stone-deck oven, 500°F', harvest: 'Baked daily at 4am' },
    macros: { fat: '1g', carbs: '36g', protein: '6g' },
    pairingIds: ['olive-oil', 'prosciutto', 'manchego'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper sleeve', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'plain-croissant',
    label: 'FRENCH',
    name: 'Plain Croissant',
    size: 'EACH',
    price: 4.00,
    category: 'bakery',
    description: '81 layers of French cultured butter dough, laminated to perfection.',
    image: '/assets/bakery2.webp',
    origin: { region: 'In-house Bakery', altitude: 'Laminated over 3 days', harvest: 'Baked fresh every morning' },
    macros: { fat: '14g', carbs: '26g', protein: '4g' },
    pairingIds: ['ethiopian-beans', 'raw-honey'],
    logistics: { freshness: 'Same-day bake', packaging: 'Wax paper sleeve', carbon: '0.15kg CO₂e per unit' },
  },
  {
    id: 'baguette',
    label: 'ARTISAN',
    name: 'Baguette',
    size: 'EACH',
    price: 4.50,
    category: 'bakery',
    description: 'Classic Parisian style with a thin, shatteringly crisp crust.',
    image: '/assets/bakery3.webp',
    origin: { region: 'In-house Bakery', altitude: 'Steam-injected stone oven', harvest: 'Baked twice daily' },
    macros: { fat: '1g', carbs: '33g', protein: '5g' },
    pairingIds: ['olive-oil', 'manchego', 'prosciutto'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper bag', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'pain-au-chocolat',
    label: 'FRENCH',
    name: 'Pain au Chocolat',
    size: 'EACH',
    price: 5.00,
    category: 'bakery',
    description: 'Buttery pastry filled with 70% dark Valrhona chocolate batons.',
    image: '/assets/bakery4.webp',
    origin: { region: 'In-house Bakery', altitude: 'Valrhona Guanaja 70% couverture', harvest: 'Baked fresh every morning' },
    macros: { fat: '16g', carbs: '30g', protein: '5g' },
    pairingIds: ['cold-brew', 'oat-latte'],
    logistics: { freshness: 'Same-day bake', packaging: 'Wax paper sleeve', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'rye-bread',
    label: 'HERITAGE',
    name: 'Rye Bread',
    size: '1 LOAF',
    price: 8.50,
    category: 'bakery',
    description: 'Dense, nutrient-heavy rye with caraway seeds and a malty finish.',
    image: '/assets/bakery5.webp',
    origin: { region: 'In-house Bakery', altitude: 'Heritage rye flour, stone-milled', harvest: 'Baked daily' },
    macros: { fat: '1g', carbs: '34g', protein: '5g' },
    pairingIds: ['prosciutto', 'manchego', 'green-olives'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper sleeve', carbon: '0.15kg CO₂e per unit' },
  },
  {
    id: 'brioche-bun',
    label: 'ENRICHED',
    name: 'Brioche Bun',
    size: 'EACH',
    price: 2.00,
    category: 'bakery',
    description: 'Enriched egg and butter dough, glazed for a golden, pillowy finish.',
    image: '/assets/bakery6.webp',
    origin: { region: 'In-house Bakery', altitude: 'Free-range eggs, cultured butter', harvest: 'Baked fresh every morning' },
    macros: { fat: '10g', carbs: '28g', protein: '5g' },
    pairingIds: ['raw-honey', 'vegan-butter'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper bag', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'focaccia-slice',
    label: 'ARTISAN',
    name: 'Focaccia Slice',
    size: 'EACH',
    price: 5.00,
    category: 'bakery',
    description: 'Infused with cold-pressed olive oil and Maldon sea salt.',
    image: '/assets/bakery7.webp',
    origin: { region: 'In-house Bakery', altitude: 'Ligurian EVOO, Maldon flakes', harvest: 'Baked daily' },
    macros: { fat: '8g', carbs: '30g', protein: '4g' },
    pairingIds: ['olive-oil', 'arugula', 'heirloom-tomato'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper wrap', carbon: '0.15kg CO₂e per unit' },
  },
  {
    id: 'ciabatta',
    label: 'ARTISAN',
    name: 'Ciabatta',
    size: 'EACH',
    price: 6.00,
    category: 'bakery',
    description: 'High-hydration dough resulting in a light, honeycomb interior.',
    image: '/assets/bakery8.webp',
    origin: { region: 'In-house Bakery', altitude: '80% hydration, slow ferment', harvest: 'Baked twice daily' },
    macros: { fat: '1g', carbs: '32g', protein: '5g' },
    pairingIds: ['olive-oil', 'prosciutto'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper bag', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'almond-croissant',
    label: 'FRENCH',
    name: 'Almond Croissant',
    size: 'EACH',
    price: 6.00,
    category: 'bakery',
    description: 'Double-baked with rum-infused almond cream and toasted slivers.',
    image: '/assets/bakery9.webp',
    origin: { region: 'In-house Bakery', altitude: 'Sicilian almonds, dark rum', harvest: 'Baked fresh every morning' },
    macros: { fat: '18g', carbs: '32g', protein: '6g' },
    pairingIds: ['oat-latte', 'ethiopian-beans'],
    logistics: { freshness: 'Same-day bake', packaging: 'Wax paper sleeve', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'multigrain-loaf',
    label: 'HERITAGE',
    name: 'Multigrain Loaf',
    size: '1 LOAF',
    price: 8.00,
    category: 'bakery',
    description: 'Packed with ancient grains, flax seeds, and toasted sunflower seeds.',
    image: '/assets/bakery10.webp',
    origin: { region: 'In-house Bakery', altitude: 'Spelt, millet, quinoa, flax blend', harvest: 'Baked daily' },
    macros: { fat: '3g', carbs: '28g', protein: '7g' },
    pairingIds: ['raw-honey', 'vegan-butter', 'hass-avocado'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper sleeve', carbon: '0.15kg CO₂e per unit' },
  },
  {
    id: 'olive-rosemary-loaf',
    label: 'ARTISAN',
    name: 'Olive Rosemary Loaf',
    size: '1 LOAF',
    price: 9.50,
    category: 'bakery',
    description: 'Stone-baked with Ligurian olives and wild rosemary, yielding a fragrant, savoury crumb.',
    image: '/assets/bakery11.webp',
    origin: { region: 'In-house Bakery', altitude: 'Taggiasca olives, wild rosemary', harvest: 'Baked daily' },
    macros: { fat: '5g', carbs: '30g', protein: '5g' },
    pairingIds: ['olive-oil', 'manchego', 'arugula'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper sleeve', carbon: '0.15kg CO₂e per unit' },
  },

  // ─── SUSHI / DELI (5) ────────────────────────────────────────
  {
    id: 'salmon-nigiri',
    label: 'SUSHI',
    name: 'Salmon Nigiri',
    size: '4 PC',
    price: 14.00,
    category: 'deli',
    description: 'Sustainable King Salmon over hand-pressed Koshihikari rice.',
    image: '/assets/sushi1.webp',
    origin: { region: 'Alaska, USA', altitude: 'Wild-caught, cold Pacific waters', harvest: 'Line-caught, ike jime processed' },
    macros: { fat: '8g', carbs: '20g', protein: '14g' },
    pairingIds: ['wasabi-root', 'maki-roll'],
    logistics: { freshness: 'Same-day preparation', packaging: 'Recycled PET tray', carbon: '1.2kg CO₂e per unit' },
  },
  {
    id: 'tuna-sashimi',
    label: 'SUSHI',
    name: 'Tuna Sashimi',
    size: '6 PC',
    price: 18.00,
    category: 'deli',
    description: 'Lean Bluefin Akami sliced for a clean, silky texture.',
    image: '/assets/sushi2.webp',
    origin: { region: 'Tsukiji Market, Japan', altitude: 'Deep-sea caught, flash-frozen', harvest: 'Grade-1 sashimi quality' },
    macros: { fat: '1g', carbs: '0g', protein: '26g' },
    pairingIds: ['wasabi-root', 'yellowtail-nigiri'],
    logistics: { freshness: 'Same-day sliced', packaging: 'Temperature-controlled tray', carbon: '2.0kg CO₂e per unit' },
  },
  {
    id: 'yellowtail-nigiri',
    label: 'SUSHI',
    name: 'Yellowtail Nigiri',
    size: '4 PC',
    price: 16.00,
    category: 'deli',
    description: 'Buttery Hamachi with a hint of citrus and wasabi.',
    image: '/assets/sushi3.webp',
    origin: { region: 'Kyushu, Japan', altitude: 'Sustainably farmed, open-water pens', harvest: 'Hand-filleted daily' },
    macros: { fat: '6g', carbs: '18g', protein: '12g' },
    pairingIds: ['salmon-nigiri', 'wasabi-root'],
    logistics: { freshness: 'Same-day preparation', packaging: 'Recycled PET tray', carbon: '1.5kg CO₂e per unit' },
  },
  {
    id: 'maki-roll',
    label: 'SUSHI',
    name: 'Maki Roll',
    size: '8 PC',
    price: 12.00,
    category: 'deli',
    description: 'A minimalist vegetable or fish roll wrapped in crisp Nori.',
    image: '/assets/sushi4.webp',
    origin: { region: 'In-house Sushi Bar', altitude: 'Hand-rolled to order', harvest: 'Ariake Sea nori sheets' },
    macros: { fat: '3g', carbs: '28g', protein: '8g' },
    pairingIds: ['salmon-nigiri', 'matcha-tonic'],
    logistics: { freshness: 'Same-day preparation', packaging: 'Recycled PET tray', carbon: '0.8kg CO₂e per unit' },
  },
  {
    id: 'wasabi-root',
    label: 'PREMIUM',
    name: 'Wasabi Root',
    size: 'EACH',
    price: 25.00,
    category: 'deli',
    description: 'Freshly grated Japanese rhizome for a clean, floral heat.',
    image: '/assets/sushi5.webp',
    origin: { region: 'Shizuoka, Japan', altitude: 'Mountain spring-fed beds, shade-grown', harvest: '18-month cultivation cycle' },
    macros: { fat: '0.6g', carbs: '24g', protein: '5g' },
    pairingIds: ['salmon-nigiri', 'tuna-sashimi'],
    logistics: { freshness: '2 weeks refrigerated', packaging: 'Damp paper wrap', carbon: '1.0kg CO₂e per unit' },
  },

  // ─── TONIC BAR / JUICE BAR (5) ───────────────────────────────
  {
    id: 'vitality-juice',
    label: 'COLD-PRESSED',
    name: 'Vitality Juice',
    size: '16 OZ',
    price: 11.00,
    category: 'juice-bar',
    description: 'Cold-pressed turmeric, ginger, and Meyer lemon.',
    image: '/assets/tonicbar1.webp',
    origin: { region: 'In-house Tonic Bar', altitude: 'Hydraulic cold-press, no heat', harvest: 'Pressed daily at 6am' },
    macros: { fat: '0.5g', carbs: '18g', protein: '1g' },
    pairingIds: ['immunity-shot', 'aloe-water'],
    logistics: { freshness: 'Same-day press', packaging: 'Glass bottle, returnable', carbon: '0.15kg CO₂e per unit' },
  },
  {
    id: 'matcha-tonic',
    label: 'CEREMONIAL',
    name: 'Matcha Tonic',
    size: '12 OZ',
    price: 8.00,
    category: 'juice-bar',
    description: 'Ceremonial grade matcha whisked with sparkling alkaline water.',
    image: '/assets/tonicbar2.webp',
    origin: { region: 'In-house Tonic Bar', altitude: 'Uji, Kyoto first-harvest matcha', harvest: 'Whisked to order' },
    macros: { fat: '0g', carbs: '4g', protein: '2g' },
    pairingIds: ['vitality-juice', 'aloe-water'],
    logistics: { freshness: 'Made to order', packaging: 'Glass bottle', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'immunity-shot',
    label: 'WELLNESS',
    name: 'Immunity Shot',
    size: '2 OZ',
    price: 5.00,
    category: 'juice-bar',
    description: 'Concentrated ginger and oil of oregano for a quick health boost.',
    image: '/assets/tonicbar3.webp',
    origin: { region: 'In-house Tonic Bar', altitude: 'Hawaiian ginger, Mediterranean oregano', harvest: 'Pressed fresh daily' },
    macros: { fat: '0g', carbs: '3g', protein: '0g' },
    pairingIds: ['vitality-juice', 'meyer-lemon'],
    logistics: { freshness: 'Same-day press', packaging: 'Glass vial', carbon: '0.05kg CO₂e per unit' },
  },
  {
    id: 'charcoal-cleanse',
    label: 'DETOX',
    name: 'Charcoal Cleanse',
    size: '16 OZ',
    price: 9.00,
    category: 'juice-bar',
    description: 'Activated charcoal with organic lemon and agave.',
    image: '/assets/tonicbar4.webp',
    origin: { region: 'In-house Tonic Bar', altitude: 'Coconut-shell activated charcoal', harvest: 'Blended fresh daily' },
    macros: { fat: '0g', carbs: '12g', protein: '0g' },
    pairingIds: ['aloe-water', 'vitality-juice'],
    logistics: { freshness: 'Same-day press', packaging: 'Glass bottle, returnable', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'aloe-water',
    label: 'HYDRATION',
    name: 'Aloe Water',
    size: '16 OZ',
    price: 7.00,
    category: 'juice-bar',
    description: 'Pure aloe extract for hydration and digestive support.',
    image: '/assets/tonicbar5.webp',
    origin: { region: 'In-house Tonic Bar', altitude: 'Organic inner-leaf aloe vera', harvest: 'Cold-extracted daily' },
    macros: { fat: '0g', carbs: '6g', protein: '0g' },
    pairingIds: ['vitality-juice', 'immunity-shot'],
    logistics: { freshness: 'Same-day extraction', packaging: 'Glass bottle, returnable', carbon: '0.1kg CO₂e per unit' },
  },

  // ─── CAFE / JUICE BAR (5) ────────────────────────────────────
  {
    id: 'ethiopian-beans',
    label: 'SINGLE ORIGIN',
    name: 'Ethiopian Beans',
    size: '12 OZ',
    price: 24.00,
    category: 'juice-bar',
    description: 'Single-origin beans with jasmine and citrus notes.',
    image: '/assets/cafe1.webp',
    origin: { region: 'Yirgacheffe, Ethiopia', altitude: '1,900m elevation, shade-grown', harvest: 'Hand-picked cherries, washed process' },
    macros: { fat: '0g', carbs: '0g', protein: '0.3g' },
    pairingIds: ['plain-croissant', 'pain-au-chocolat'],
    logistics: { freshness: 'Roasted within 7 days', packaging: 'Resealable kraft bag with valve', carbon: '1.5kg CO₂e per unit' },
  },
  {
    id: 'ceremonial-matcha',
    label: 'CEREMONIAL',
    name: 'Ceremonial Matcha',
    size: '30G TIN',
    price: 35.00,
    category: 'juice-bar',
    description: 'First-harvest Uji matcha for a calm, focused energy.',
    image: '/assets/cafe2.webp',
    origin: { region: 'Uji, Kyoto, Japan', altitude: 'Shade-grown 21 days, stone-milled', harvest: 'First flush, spring harvest only' },
    macros: { fat: '0.3g', carbs: '4g', protein: '3g' },
    pairingIds: ['oat-milk', 'almond-croissant'],
    logistics: { freshness: 'Milled within 30 days', packaging: 'Sealed tin, nitrogen-flushed', carbon: '0.8kg CO₂e per unit' },
  },
  {
    id: 'cold-brew',
    label: 'SLOW-STEEPED',
    name: 'Cold Brew',
    size: '16 OZ',
    price: 6.00,
    category: 'juice-bar',
    description: '12-hour steep for a low-acidity, chocolatey finish.',
    image: '/assets/cafe3.webp',
    origin: { region: 'In-house Cafe', altitude: 'Colombian single-origin, coarse grind', harvest: 'Steeped 12 hours in cold water' },
    macros: { fat: '0g', carbs: '0g', protein: '0.5g' },
    pairingIds: ['oat-milk', 'pain-au-chocolat'],
    logistics: { freshness: 'Brewed daily', packaging: 'Glass bottle', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'oat-latte',
    label: 'HOUSE',
    name: 'Oat Latte',
    size: '12 OZ',
    price: 6.50,
    category: 'juice-bar',
    description: 'Double espresso with house-made creamy oat milk.',
    image: '/assets/cafe4.webp',
    origin: { region: 'In-house Cafe', altitude: 'Ethiopian blend, house-made oat milk', harvest: 'Pulled to order' },
    macros: { fat: '5g', carbs: '16g', protein: '3g' },
    pairingIds: ['almond-croissant', 'plain-croissant'],
    logistics: { freshness: 'Made to order', packaging: 'Ceramic cup / compostable to-go', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'earl-grey-tea',
    label: 'LOOSE LEAF',
    name: 'Earl Grey Tea',
    size: '2 OZ TIN',
    price: 5.00,
    category: 'juice-bar',
    description: 'Bergamot-infused black tea for a sophisticated morning ritual.',
    image: '/assets/cafe5.webp',
    origin: { region: 'Darjeeling, India', altitude: '2,000m elevation, first flush', harvest: 'Hand-plucked, sun-withered' },
    macros: { fat: '0g', carbs: '0g', protein: '0g' },
    pairingIds: ['raw-honey', 'shortbread', 'meyer-lemon'],
    logistics: { freshness: 'Sealed within 48 hours of drying', packaging: 'Tin canister, resealable', carbon: '0.5kg CO₂e per unit' },
  },

  // ─── THE DELI (3) ────────────────────────────────────────────
  {
    id: 'prosciutto',
    label: 'DOP',
    name: 'Prosciutto',
    size: '4 OZ',
    price: 18.00,
    category: 'deli',
    description: '24-month aged Parma ham, sliced paper-thin.',
    image: '/assets/deli1.webp',
    origin: { region: 'Parma, Italy', altitude: 'Apennine mountain air-cured', harvest: '24-month aging, hand-sliced' },
    macros: { fat: '8g', carbs: '0g', protein: '12g' },
    pairingIds: ['manchego', 'green-olives', 'baguette'],
    logistics: { freshness: 'Sliced to order', packaging: 'Vacuum-sealed parchment', carbon: '1.8kg CO₂e per unit' },
  },
  {
    id: 'manchego',
    label: 'AGED',
    name: 'Manchego',
    size: '6 OZ',
    price: 14.00,
    category: 'deli',
    description: "Firm sheep's milk cheese with a nutty, piquant profile.",
    image: '/assets/deli2.webp',
    origin: { region: 'La Mancha, Spain', altitude: 'Manchega sheep, raw milk', harvest: '6-month cave aging' },
    macros: { fat: '16g', carbs: '0.5g', protein: '12g' },
    pairingIds: ['prosciutto', 'green-olives', 'raw-honey'],
    logistics: { freshness: 'Cut to order', packaging: 'Wax paper wrap', carbon: '1.2kg CO₂e per unit' },
  },
  {
    id: 'green-olives',
    label: 'SICILIAN',
    name: 'Green Olives',
    size: '8 OZ',
    price: 9.00,
    category: 'deli',
    description: 'Buttery Castelvetrano olives from Sicily.',
    image: '/assets/deli3.webp',
    origin: { region: 'Castelvetrano, Sicily', altitude: 'Mediterranean hillside groves', harvest: 'Hand-picked, brine-cured' },
    macros: { fat: '10g', carbs: '3g', protein: '1g' },
    pairingIds: ['prosciutto', 'manchego', 'focaccia-slice'],
    logistics: { freshness: '6-month brine cure', packaging: 'Glass jar, reusable', carbon: '0.6kg CO₂e per unit' },
  },

  // ─── THE PANTRY (5) ──────────────────────────────────────────
  {
    id: 'olive-oil',
    label: 'EVOO',
    name: 'Olive Oil',
    size: '500 ML',
    price: 30.00,
    category: 'pantry',
    description: 'First-press, cold-extracted organic EVOO.',
    image: '/assets/pantry1.webp',
    origin: { region: 'Puglia, Italy', altitude: 'Coratina olives, stone-milled', harvest: 'First cold press, November harvest' },
    macros: { fat: '14g', carbs: '0g', protein: '0g' },
    pairingIds: ['sourdough-boule', 'sea-salt', 'baguette'],
    logistics: { freshness: 'Current harvest year', packaging: 'Dark glass bottle, UV-protected', carbon: '0.8kg CO₂e per unit' },
  },
  {
    id: 'sea-salt',
    label: 'FLAKE',
    name: 'Sea Salt',
    size: '250G',
    price: 8.00,
    category: 'pantry',
    description: 'Pyramidal Maldon flakes for the perfect crunch.',
    image: '/assets/pantry2.webp',
    origin: { region: 'Maldon, Essex, UK', altitude: 'Blackwater estuary evaporation pans', harvest: 'Hand-harvested, sun-dried' },
    macros: { fat: '0g', carbs: '0g', protein: '0g' },
    pairingIds: ['olive-oil', 'hass-avocado', 'dark-chocolate'],
    logistics: { freshness: 'Shelf-stable 2 years', packaging: 'Recycled cardboard box', carbon: '0.3kg CO₂e per unit' },
  },
  {
    id: 'raw-honey',
    label: 'RAW',
    name: 'Raw Honey',
    size: '12 OZ',
    price: 25.00,
    category: 'pantry',
    description: 'Unfiltered wildflower honey with active enzymes.',
    image: '/assets/pantry3.webp',
    origin: { region: 'Hudson Valley, NY', altitude: 'Wildflower meadow apiaries', harvest: 'Cold-extracted, never heated above 95°F' },
    macros: { fat: '0g', carbs: '17g', protein: '0g' },
    pairingIds: ['plain-croissant', 'earl-grey-tea', 'manchego'],
    logistics: { freshness: 'Shelf-stable 2+ years', packaging: 'Glass jar, reusable', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'balsamic',
    label: 'AGED',
    name: 'Balsamic',
    size: '250 ML',
    price: 45.00,
    category: 'pantry',
    description: 'Aged 15 years in oak barrels for a syrupy finish.',
    image: '/assets/pantry4.webp',
    origin: { region: 'Modena, Italy', altitude: 'DOP certified, Trebbiano grapes', harvest: '15-year barrel aging, 5 wood progression' },
    macros: { fat: '0g', carbs: '14g', protein: '0g' },
    pairingIds: ['arugula', 'manchego', 'heirloom-tomato'],
    logistics: { freshness: 'Shelf-stable indefinitely', packaging: 'Glass bottle, wax seal', carbon: '0.5kg CO₂e per unit' },
  },
  {
    id: 'dijon-mustard',
    label: 'FRENCH',
    name: 'Dijon Mustard',
    size: '7 OZ',
    price: 7.00,
    category: 'pantry',
    description: 'Authentic sharp stone-ground mustard from France.',
    image: '/assets/pantry5.webp',
    origin: { region: 'Dijon, France', altitude: 'Brown mustard seed, verjuice base', harvest: 'Stone-ground in small batches' },
    macros: { fat: '3g', carbs: '1g', protein: '2g' },
    pairingIds: ['prosciutto', 'baguette'],
    logistics: { freshness: 'Shelf-stable 18 months', packaging: 'Glass jar', carbon: '0.3kg CO₂e per unit' },
  },

  // ─── DAIRY ALT (5) ───────────────────────────────────────────
  {
    id: 'oat-milk',
    label: 'HOUSE-MADE',
    name: 'Oat Milk',
    size: '32 OZ',
    price: 8.00,
    category: 'dairy-alt',
    description: 'Pressed daily with zero gums or thickeners.',
    image: '/assets/dairyalt1.webp',
    origin: { region: 'In-house Dairy Lab', altitude: 'Scandinavian oats, triple-filtered', harvest: 'Pressed fresh daily' },
    macros: { fat: '5g', carbs: '16g', protein: '3g' },
    pairingIds: ['ethiopian-beans', 'cold-brew', 'ceremonial-matcha'],
    logistics: { freshness: '5 days refrigerated', packaging: 'Glass bottle, returnable', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'almond-milk',
    label: 'HOUSE-MADE',
    name: 'Almond Milk',
    size: '32 OZ',
    price: 8.00,
    category: 'dairy-alt',
    description: '25% almond content for a rich, nutty flavor.',
    image: '/assets/dairyalt2.webp',
    origin: { region: 'In-house Dairy Lab', altitude: 'Sicilian almonds, cold-pressed', harvest: 'Pressed fresh daily' },
    macros: { fat: '8g', carbs: '3g', protein: '4g' },
    pairingIds: ['ethiopian-beans', 'ceremonial-matcha'],
    logistics: { freshness: '5 days refrigerated', packaging: 'Glass bottle, returnable', carbon: '0.3kg CO₂e per unit' },
  },
  {
    id: 'cashew-yogurt',
    label: 'CULTURED',
    name: 'Cashew Yogurt',
    size: '16 OZ',
    price: 6.00,
    category: 'dairy-alt',
    description: 'Cultured cashew base with live probiotics.',
    image: '/assets/dairyalt3.webp',
    origin: { region: 'In-house Dairy Lab', altitude: 'Vietnamese cashews, 6 probiotic strains', harvest: '48-hour fermentation cycle' },
    macros: { fat: '10g', carbs: '8g', protein: '4g' },
    pairingIds: ['blueberry', 'raw-honey'],
    logistics: { freshness: '7 days refrigerated', packaging: 'Glass jar, returnable', carbon: '0.3kg CO₂e per unit' },
  },
  {
    id: 'vegan-butter',
    label: 'CULTURED',
    name: 'Vegan Butter',
    size: '8 OZ',
    price: 7.00,
    category: 'dairy-alt',
    description: 'Cultured plant fats that spread like cultured cream.',
    image: '/assets/dairyalt4.webp',
    origin: { region: 'In-house Dairy Lab', altitude: 'Coconut oil, cashew cream, cultures', harvest: 'Churned in small batches' },
    macros: { fat: '11g', carbs: '0g', protein: '0g' },
    pairingIds: ['sourdough-boule', 'brioche-bun'],
    logistics: { freshness: '14 days refrigerated', packaging: 'Compostable tub', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'coconut-cream',
    label: 'ORGANIC',
    name: 'Coconut Cream',
    size: '13.5 OZ',
    price: 5.00,
    category: 'dairy-alt',
    description: 'High-fat organic coconut extract for rich desserts.',
    image: '/assets/dairyalt5.webp',
    origin: { region: 'Sri Lanka', altitude: 'Organic coconut plantations', harvest: 'Cold-pressed, first extraction' },
    macros: { fat: '24g', carbs: '3g', protein: '2g' },
    pairingIds: ['dark-chocolate', 'matcha-tonic'],
    logistics: { freshness: 'Shelf-stable 18 months', packaging: 'BPA-free can', carbon: '0.4kg CO₂e per unit' },
  },

  // ─── SWEET TREATS (4) ────────────────────────────────────────
  {
    id: 'dark-chocolate',
    label: 'SINGLE ORIGIN',
    name: 'Dark Chocolate',
    size: '3.5 OZ',
    price: 9.00,
    category: 'sweet-treats',
    description: '70% single-origin cacao with notes of tobacco.',
    image: '/assets/sweet1.webp',
    origin: { region: 'Piura, Peru', altitude: '800m elevation, Nacional cacao', harvest: 'Single-estate, hand-fermented' },
    macros: { fat: '12g', carbs: '14g', protein: '2g' },
    pairingIds: ['sea-salt', 'cold-brew', 'coconut-cream'],
    logistics: { freshness: 'Shelf-stable 12 months', packaging: 'Recycled foil, paper sleeve', carbon: '0.5kg CO₂e per unit' },
  },
  {
    id: 'dark-truffle',
    label: 'RAW',
    name: 'Dark Truffle',
    size: '6 PC',
    price: 15.00,
    category: 'sweet-treats',
    description: 'Raw cacao and dates rolled in sea salt.',
    image: '/assets/sweet2.webp',
    origin: { region: 'In-house Confectionery', altitude: 'Peruvian raw cacao, Medjool dates', harvest: 'Hand-rolled daily' },
    macros: { fat: '8g', carbs: '18g', protein: '2g' },
    pairingIds: ['dark-chocolate', 'cold-brew'],
    logistics: { freshness: '7 days refrigerated', packaging: 'Recycled kraft box', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'shortbread',
    label: 'SCOTTISH',
    name: 'Shortbread',
    size: '6 PC',
    price: 10.00,
    category: 'sweet-treats',
    description: 'Buttery, crumbly biscuits with a hint of vanilla.',
    image: '/assets/sweet3.webp',
    origin: { region: 'In-house Bakery', altitude: 'French butter, Tahitian vanilla', harvest: 'Baked in small batches' },
    macros: { fat: '10g', carbs: '16g', protein: '2g' },
    pairingIds: ['earl-grey-tea', 'raw-honey'],
    logistics: { freshness: '10 days in tin', packaging: 'Recycled tin', carbon: '0.15kg CO₂e per unit' },
  },
  {
    id: 'dried-mango',
    label: 'ORGANIC',
    name: 'Dried Mango',
    size: '4 OZ',
    price: 8.00,
    category: 'sweet-treats',
    description: 'Sun-dried fruit with no added sugars or sulfur.',
    image: '/assets/sweet4.webp',
    origin: { region: 'Cebu, Philippines', altitude: 'Carabao mango, sun-dried 5 days', harvest: 'Peak-season fruit, hand-sliced' },
    macros: { fat: '0g', carbs: '28g', protein: '1g' },
    pairingIds: ['cashew-yogurt', 'dark-chocolate'],
    logistics: { freshness: 'Shelf-stable 6 months', packaging: 'Compostable pouch', carbon: '0.4kg CO₂e per unit' },
  },
];

// ─── PAIRINGS HELPER ───────────────────────────────────────────
export function getPairings(product: Product): Product[] {
  const explicit = product.pairingIds
    .map((id) => products.find((p) => p.id === id))
    .filter((p): p is Product => !!p);

  if (explicit.length >= 6) return explicit.slice(0, 6);

  const sameCat = products.filter(
    (p) => p.category === product.category && p.id !== product.id && !product.pairingIds.includes(p.id)
  );

  return [...explicit, ...sameCat].slice(0, 6);
}
