export interface NutritionMacros {
  fat: string;
  carbs: string;
  protein: string;
}

export interface Product {
  id: string;
  label: string;
  name: string;
  size: string;
  price: number;
  category: 'produce' | 'dairy-alt' | 'bakery' | 'juice-bar' | 'pantry' | 'sweet-treats' | 'deli';
  description: string;
  image: string;
  origin: {
    region: string;
    altitude: string;
    harvest: string;
  };
  macros: NutritionMacros;
  pairingIds: string[];
  logistics: {
    freshness: string;
    packaging: string;
    carbon: string;
  };
}

export const products: Product[] = [
  // ─── PRODUCE (8) ───────────────────────────────────────────────
  {
    id: 'hass-avocados',
    label: 'ORGANIC',
    name: 'Hass Avocados',
    size: '3PK',
    price: 7.50,
    category: 'produce',
    description: 'Hand-selected for perfect ripeness. Creamy, rich texture with a buttery finish sourced from high-altitude volcanic groves where altitude stress produces dramatically higher oil content.',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d85f6a?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Michoacán, Mexico',
      altitude: '2,200m elevation, volcanic soil',
      harvest: 'Hand-picked at peak ripeness, inspected individually',
    },
    macros: { fat: '15g', carbs: '9g', protein: '2g' },
    pairingIds: ['sourdough-bread', 'olive-oil', 'mixed-tomatoes'],
    logistics: {
      freshness: '5–7 days from harvest',
      packaging: 'Recycled kraft tray, compostable wrap',
      carbon: '0.8kg CO₂e per unit',
    },
  },
  {
    id: 'mixed-tomatoes',
    label: 'HEIRLOOM',
    name: 'Mixed Tomatoes',
    size: '1LB',
    price: 5.00,
    category: 'produce',
    description: 'A seasonal assortment of vine-ripened varieties. Each variety is selected for its unique balance of acidity and sugar from volcanic plains beneath Vesuvius.',
    image: 'https://images.unsplash.com/photo-1546470427-0d4db154ceb8?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'San Marzano, Campania',
      altitude: 'Volcanic plains beneath Vesuvius',
      harvest: 'Daily hand-harvest, vine-attached transport',
    },
    macros: { fat: '0.2g', carbs: '3.9g', protein: '0.9g' },
    pairingIds: ['olive-oil', 'hass-avocados', 'sourdough-bread'],
    logistics: {
      freshness: '3–4 days from harvest',
      packaging: 'Single-layer wooden flat, no plastic',
      carbon: '0.3kg CO₂e per unit',
    },
  },
  {
    id: 'fresh-blueberries',
    label: 'ORGANIC',
    name: 'Fresh Blueberries',
    size: '6OZ',
    price: 4.00,
    category: 'produce',
    description: 'Plump, hand-picked berries from coastal farms. Deeply pigmented from maritime climate and rich alluvial soil with a balanced tart-to-sweet profile.',
    image: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Willamette Valley, Oregon',
      altitude: 'Sea-level coastal microclimate',
      harvest: 'Hand-picked at dawn, cold-chain within 2 hours',
    },
    macros: { fat: '0.3g', carbs: '14g', protein: '0.7g' },
    pairingIds: ['manuka-honey', 'oat-milk', 'green-juice'],
    logistics: {
      freshness: '5–7 days refrigerated',
      packaging: 'Ventilated PET clamshell, recyclable',
      carbon: '0.2kg CO₂e per unit',
    },
  },
  {
    id: 'rainbow-chard',
    label: 'ORGANIC',
    name: 'Rainbow Chard',
    size: '1 BUNCH',
    price: 3.50,
    category: 'produce',
    description: 'Vibrant stalks in ruby, gold, and ivory with tender mineral-rich leaves. Harvested at first light from biodynamic raised beds for peak nutrient density.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Salinas Valley, California',
      altitude: 'Coastal lowland, sandy loam soil',
      harvest: 'Cut at dawn, hydro-cooled on site',
    },
    macros: { fat: '0.2g', carbs: '3.7g', protein: '1.8g' },
    pairingIds: ['olive-oil', 'garlic-confit', 'sourdough-bread'],
    logistics: {
      freshness: '4–5 days refrigerated',
      packaging: 'Compostable cellulose band',
      carbon: '0.15kg CO₂e per unit',
    },
  },
  {
    id: 'medjool-dates',
    label: 'ORGANIC',
    name: 'Medjool Dates',
    size: '12OZ',
    price: 9.00,
    category: 'produce',
    description: 'Plump, caramel-soft dates with a deep toffee sweetness. Each fruit is hand-sorted for size and moisture, delivering melt-in-your-mouth richness.',
    image: 'https://images.unsplash.com/photo-1610300033033-63e3a973451a?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Coachella Valley, California',
      altitude: 'Below sea level, extreme desert heat',
      harvest: 'Hand-harvested over 6-week ripening window',
    },
    macros: { fat: '0.2g', carbs: '75g', protein: '1.8g' },
    pairingIds: ['almond-butter', 'dark-chocolate', 'tahini'],
    logistics: {
      freshness: '6 months at room temperature',
      packaging: 'Recycled PET tray, resealable lid',
      carbon: '0.25kg CO₂e per unit',
    },
  },
  {
    id: 'lacinato-kale',
    label: 'ORGANIC',
    name: 'Lacinato Kale',
    size: '1 BUNCH',
    price: 3.00,
    category: 'produce',
    description: 'Deeply textured dinosaur kale with a robust, slightly sweet flavor. Frost-kissed leaves develop extra sweetness through natural cold stress.',
    image: 'https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Tuscany, Italy',
      altitude: 'Hill farms at 400m elevation',
      harvest: 'Cut after first frost for peak sweetness',
    },
    macros: { fat: '0.9g', carbs: '8.8g', protein: '4.3g' },
    pairingIds: ['olive-oil', 'garlic-confit', 'lemon-vinaigrette'],
    logistics: {
      freshness: '5–7 days refrigerated',
      packaging: 'Compostable wrap, rubber band',
      carbon: '0.18kg CO₂e per unit',
    },
  },
  {
    id: 'chanterelle-mushrooms',
    label: 'WILD-FORAGED',
    name: 'Chanterelle Mushrooms',
    size: '4OZ',
    price: 14.00,
    category: 'produce',
    description: 'Golden, trumpet-shaped wild mushrooms with an apricot-like fragrance. Foraged from old-growth Pacific Northwest forests after autumn rains.',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Olympic Peninsula, Washington',
      altitude: '300–800m elevation, old-growth conifer forest',
      harvest: 'Hand-foraged by certified wildcrafters',
    },
    macros: { fat: '0.5g', carbs: '6.9g', protein: '1.5g' },
    pairingIds: ['sourdough-bread', 'olive-oil', 'gruyere-wedge'],
    logistics: {
      freshness: '3–5 days refrigerated',
      packaging: 'Wax-lined paper bag, breathable',
      carbon: '0.1kg CO₂e per unit',
    },
  },
  {
    id: 'fuji-apples',
    label: 'ORGANIC',
    name: 'Fuji Apples',
    size: '3LB BAG',
    price: 6.50,
    category: 'produce',
    description: 'Exceptionally crisp and honey-sweet apples from high-altitude orchards. Cool mountain nights concentrate sugars for an intense, floral sweetness.',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Aomori Prefecture, Japan',
      altitude: '500m elevation, volcanic ash soil',
      harvest: 'Hand-picked October–November, individually wrapped',
    },
    macros: { fat: '0.2g', carbs: '14g', protein: '0.3g' },
    pairingIds: ['almond-butter', 'sharp-cheddar', 'manuka-honey'],
    logistics: {
      freshness: '3–4 weeks refrigerated',
      packaging: 'Recycled mesh bag',
      carbon: '0.35kg CO₂e per unit',
    },
  },

  // ─── BAKERY (8) ────────────────────────────────────────────────
  {
    id: 'sourdough-bread',
    label: 'ARTISAN',
    name: 'Sourdough Bread',
    size: 'LOAF',
    price: 8.50,
    category: 'bakery',
    description: 'Traditionally fermented for 24 hours using heritage flour. Our 14-year-old starter is fed twice daily with stone-milled wheat for a deep, caramelized crust.',
    image: 'https://images.unsplash.com/photo-1585478259715-876acc5be8eb?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'San Francisco, California',
      altitude: 'Coastal fog belt, ideal fermentation climate',
      harvest: 'Heritage wheat, stone-milled to order',
    },
    macros: { fat: '1.2g', carbs: '52g', protein: '9g' },
    pairingIds: ['hass-avocados', 'olive-oil', 'sharp-cheddar'],
    logistics: {
      freshness: 'Baked daily, best within 48 hours',
      packaging: 'Unbleached paper bag, cotton tie',
      carbon: '0.3kg CO₂e per unit',
    },
  },
  {
    id: 'pain-au-chocolat',
    label: 'VIENNOISERIE',
    name: 'Pain au Chocolat',
    size: '2PK',
    price: 6.50,
    category: 'bakery',
    description: 'Flaky, laminated pastry with batons of Valrhona dark chocolate. Hand-folded through 27 layers of cultured butter dough and baked to a shattering golden finish.',
    image: 'https://images.unsplash.com/photo-1530610476181-d83430b64dcd?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Paris, Île-de-France',
      altitude: 'Traditional French boulangerie method',
      harvest: 'Normandy butter, Guanaja chocolate batons',
    },
    macros: { fat: '18g', carbs: '35g', protein: '5g' },
    pairingIds: ['oat-milk', 'cold-brew-concentrate', 'fresh-blueberries'],
    logistics: {
      freshness: 'Baked before dawn, best same day',
      packaging: 'Glassine-lined paper bag',
      carbon: '0.4kg CO₂e per unit',
    },
  },
  {
    id: 'everything-bagels',
    label: 'ARTISAN',
    name: 'Everything Bagels',
    size: '4PK',
    price: 7.00,
    category: 'bakery',
    description: 'Kettle-boiled and wood-fired with a generous coating of sesame, poppy, garlic, onion, and flaky salt. Dense, chewy crumb with a properly blistered crust.',
    image: 'https://images.unsplash.com/photo-1585535358816-de544002c967?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Brooklyn, New York',
      altitude: 'NYC tap water, naturally soft and ideal for dough',
      harvest: 'Heritage high-gluten flour, 24-hour cold ferment',
    },
    macros: { fat: '1.5g', carbs: '56g', protein: '10g' },
    pairingIds: ['cashew-cream-cheese', 'smoked-salmon', 'hass-avocados'],
    logistics: {
      freshness: 'Baked daily, best within 24 hours',
      packaging: 'Recycled kraft paper bag',
      carbon: '0.25kg CO₂e per unit',
    },
  },
  {
    id: 'olive-focaccia',
    label: 'ARTISAN',
    name: 'Olive Focaccia',
    size: 'HALF SHEET',
    price: 9.00,
    category: 'bakery',
    description: 'Pillowy focaccia studded with Castelvetrano olives and rosemary, drizzled with finishing oil. A 48-hour cold ferment develops extraordinary open crumb and complex flavor.',
    image: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Liguria, Italy',
      altitude: 'Coastal Mediterranean technique',
      harvest: 'Tipo 0 flour, Taggiasca olives',
    },
    macros: { fat: '8g', carbs: '44g', protein: '7g' },
    pairingIds: ['olive-oil', 'mixed-tomatoes', 'gruyere-wedge'],
    logistics: {
      freshness: 'Baked daily, best within 24 hours',
      packaging: 'Compostable kraft box',
      carbon: '0.3kg CO₂e per unit',
    },
  },
  {
    id: 'morning-scones',
    label: 'FRESH-BAKED',
    name: 'Lemon Poppy Scones',
    size: '2PK',
    price: 5.50,
    category: 'bakery',
    description: 'Tender, crumbly scones brightened with Meyer lemon zest and speckled with poppy seeds. Finished with a thin citrus glaze that cracks on first bite.',
    image: 'https://images.unsplash.com/photo-1486427944544-d2c246c4df14?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Napa Valley, California',
      altitude: 'Pastured butter, local Meyer lemons',
      harvest: 'Seasonal citrus, milled poppy from Tasmania',
    },
    macros: { fat: '14g', carbs: '38g', protein: '5g' },
    pairingIds: ['manuka-honey', 'oat-milk', 'golden-milk-latte'],
    logistics: {
      freshness: 'Baked before dawn, best same day',
      packaging: 'Compostable box with window',
      carbon: '0.2kg CO₂e per unit',
    },
  },
  {
    id: 'multigrain-loaf',
    label: 'WHOLE GRAIN',
    name: 'Multigrain Harvest Loaf',
    size: 'LOAF',
    price: 9.50,
    category: 'bakery',
    description: 'A hearty blend of seven heritage grains including spelt, millet, and flax. Slow-fermented for 18 hours to unlock deep nutty flavors and ensure gentle digestion.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Skagit Valley, Washington',
      altitude: 'Pacific Northwest grain shed',
      harvest: 'Stone-milled heritage grains from regenerative farms',
    },
    macros: { fat: '3g', carbs: '42g', protein: '11g' },
    pairingIds: ['almond-butter', 'hass-avocados', 'smoked-salmon'],
    logistics: {
      freshness: 'Baked daily, best within 3 days',
      packaging: 'Unbleached paper, beeswax seal',
      carbon: '0.2kg CO₂e per unit',
    },
  },
  {
    id: 'almond-croissant',
    label: 'VIENNOISERIE',
    name: 'Almond Croissant',
    size: '1PK',
    price: 5.50,
    category: 'bakery',
    description: 'A twice-baked croissant soaked in almond syrup, filled with frangipane, and topped with sliced Marcona almonds. Shatteringly crisp outside, custardy within.',
    image: 'https://images.unsplash.com/photo-1623334044303-241021148842?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Lyon, France',
      altitude: 'Traditional pâtisserie technique',
      harvest: 'Marcona almonds, AOP Charentes butter',
    },
    macros: { fat: '22g', carbs: '40g', protein: '8g' },
    pairingIds: ['oat-milk', 'cold-brew-concentrate', 'fresh-blueberries'],
    logistics: {
      freshness: 'Baked each morning, best same day',
      packaging: 'Glassine bag, compostable',
      carbon: '0.35kg CO₂e per unit',
    },
  },
  {
    id: 'seeded-crackers',
    label: 'ARTISAN',
    name: 'Seeded Flatbread Crackers',
    size: '5OZ',
    price: 6.00,
    category: 'bakery',
    description: 'Paper-thin crackers loaded with flax, sesame, and sunflower seeds. Baked in small batches until deeply golden and shatteringly crisp.',
    image: 'https://images.unsplash.com/photo-1590080876351-941da357b652?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Copenhagen, Denmark',
      altitude: 'Scandinavian knäckebröd tradition',
      harvest: 'Nordic seeds, stoneground rye flour',
    },
    macros: { fat: '9g', carbs: '28g', protein: '6g' },
    pairingIds: ['sharp-cheddar', 'cashew-cream-cheese', 'olive-oil'],
    logistics: {
      freshness: '3-month shelf life',
      packaging: 'Recyclable kraft box, inner parchment',
      carbon: '0.15kg CO₂e per unit',
    },
  },

  // ─── JUICE BAR (8) ─────────────────────────────────────────────
  {
    id: 'green-juice',
    label: 'COLD-PRESSED',
    name: 'Green Juice',
    size: '12OZ',
    price: 9.00,
    category: 'juice-bar',
    description: 'A crisp blend of kale, cucumber, and apple with a hint of ginger. Raw, unpasteurized, and extracted daily using hydraulic cold-press at 6,000 PSI.',
    image: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Hudson Valley, New York',
      altitude: 'Three organic farms within 40-mile radius',
      harvest: 'Pressed same morning as harvest',
    },
    macros: { fat: '0g', carbs: '6g', protein: '1g' },
    pairingIds: ['fresh-blueberries', 'oat-milk', 'manuka-honey'],
    logistics: {
      freshness: '72 hours from press',
      packaging: 'Glass bottle, aluminum cap, fully recyclable',
      carbon: '0.5kg CO₂e per unit',
    },
  },
  {
    id: 'turmeric-tonic',
    label: 'COLD-PRESSED',
    name: 'Turmeric Ginger Tonic',
    size: '12OZ',
    price: 10.00,
    category: 'juice-bar',
    description: 'A fiery anti-inflammatory shot expanded to a full bottle. Fresh turmeric root, ginger, lemon, and a crack of black pepper for maximum curcumin absorption.',
    image: 'https://images.unsplash.com/photo-1615478503562-ec2d8aa0a24e?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Kauai, Hawaii',
      altitude: 'Tropical lowland, volcanic soil',
      harvest: 'Hand-dug turmeric, cold-pressed same day',
    },
    macros: { fat: '0g', carbs: '8g', protein: '0.5g' },
    pairingIds: ['manuka-honey', 'green-juice', 'coconut-yogurt'],
    logistics: {
      freshness: '72 hours from press',
      packaging: 'Amber glass bottle, BPA-free cap',
      carbon: '0.4kg CO₂e per unit',
    },
  },
  {
    id: 'cold-brew-concentrate',
    label: 'SINGLE ORIGIN',
    name: 'Cold Brew Concentrate',
    size: '16OZ',
    price: 12.00,
    category: 'juice-bar',
    description: 'Steeped for 20 hours in filtered water for ultra-smooth extraction. A chocolatey, low-acid concentrate that dilutes 1:1 for the perfect cup.',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Huila, Colombia',
      altitude: '1,800m elevation, shade-grown',
      harvest: 'Washed process, single-farm lot',
    },
    macros: { fat: '0g', carbs: '0g', protein: '0.3g' },
    pairingIds: ['oat-milk', 'pain-au-chocolat', 'almond-croissant'],
    logistics: {
      freshness: '14 days refrigerated',
      packaging: 'Glass bottle, steel cap',
      carbon: '0.6kg CO₂e per unit',
    },
  },
  {
    id: 'watermelon-mint',
    label: 'COLD-PRESSED',
    name: 'Watermelon Mint Agua Fresca',
    size: '16OZ',
    price: 8.00,
    category: 'juice-bar',
    description: 'Cooling and hydrating with nothing but ripe watermelon, fresh mint, and a squeeze of lime. A summer staple pressed to order.',
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Hermiston, Oregon',
      altitude: 'High desert, irrigated alluvial soil',
      harvest: 'Peak-season melons, vine-ripened only',
    },
    macros: { fat: '0g', carbs: '12g', protein: '0.6g' },
    pairingIds: ['fresh-blueberries', 'coconut-yogurt', 'medjool-dates'],
    logistics: {
      freshness: '24 hours from press',
      packaging: 'Compostable PLA cup, paper straw',
      carbon: '0.15kg CO₂e per unit',
    },
  },
  {
    id: 'golden-milk-latte',
    label: 'HOUSE-MADE',
    name: 'Golden Milk Latte',
    size: '12OZ',
    price: 7.50,
    category: 'juice-bar',
    description: 'Warm oat milk infused with turmeric, cinnamon, cardamom, and a touch of maple. Frothed to a velvety finish with anti-inflammatory spice complexity.',
    image: 'https://images.unsplash.com/photo-1578020190125-f4f7c18bc9cb?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Kerala, India',
      altitude: 'Spice gardens of the Western Ghats',
      harvest: 'House-ground spice blend, organic turmeric root',
    },
    macros: { fat: '4g', carbs: '18g', protein: '2g' },
    pairingIds: ['oat-milk', 'morning-scones', 'manuka-honey'],
    logistics: {
      freshness: 'Made to order',
      packaging: 'Ceramic mug (dine-in) or compostable cup',
      carbon: '0.2kg CO₂e per unit',
    },
  },
  {
    id: 'berry-smoothie',
    label: 'SUPERFOOD',
    name: 'Açaí Berry Smoothie',
    size: '16OZ',
    price: 11.00,
    category: 'juice-bar',
    description: 'Flash-frozen açaí blended with banana, blueberries, and housemade cashew milk. Topped with bee pollen and hemp hearts for sustained energy.',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Pará, Brazil',
      altitude: 'Amazon floodplain, wild-harvested palms',
      harvest: 'Flash-frozen within 24 hours of harvest',
    },
    macros: { fat: '6g', carbs: '34g', protein: '4g' },
    pairingIds: ['fresh-blueberries', 'manuka-honey', 'coconut-yogurt'],
    logistics: {
      freshness: 'Blended to order',
      packaging: 'Compostable PLA cup, bamboo spoon',
      carbon: '0.7kg CO₂e per unit',
    },
  },
  {
    id: 'celery-juice',
    label: 'COLD-PRESSED',
    name: 'Celery Juice',
    size: '12OZ',
    price: 8.50,
    category: 'juice-bar',
    description: 'Pure celery, nothing else. Hydraulic cold-pressed from organic Pascal celery for maximum mineral extraction and a clean, vegetal finish.',
    image: 'https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Oxnard, California',
      altitude: 'Coastal plain, mineral-rich sandy loam',
      harvest: 'Harvested at dawn, pressed within 4 hours',
    },
    macros: { fat: '0g', carbs: '4g', protein: '0.7g' },
    pairingIds: ['green-juice', 'turmeric-tonic', 'everything-bagels'],
    logistics: {
      freshness: '48 hours from press',
      packaging: 'Glass bottle, aluminum cap',
      carbon: '0.3kg CO₂e per unit',
    },
  },
  {
    id: 'matcha-latte',
    label: 'CEREMONIAL',
    name: 'Matcha Latte',
    size: '12OZ',
    price: 7.00,
    category: 'juice-bar',
    description: 'Ceremonial-grade matcha whisked with oat milk for a creamy, umami-rich latte. Stone-ground tencha leaves from a fifth-generation tea family.',
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Uji, Kyoto Prefecture',
      altitude: 'Shade-grown at 200m elevation',
      harvest: 'First flush spring harvest, hand-picked',
    },
    macros: { fat: '3g', carbs: '10g', protein: '2g' },
    pairingIds: ['oat-milk', 'almond-croissant', 'dark-chocolate'],
    logistics: {
      freshness: 'Made to order',
      packaging: 'Ceramic mug or compostable cup',
      carbon: '0.35kg CO₂e per unit',
    },
  },

  // ─── PANTRY (8) ────────────────────────────────────────────────
  {
    id: 'manuka-honey',
    label: 'RAW',
    name: 'Manuka Honey',
    size: '8.8OZ',
    price: 28.00,
    category: 'pantry',
    description: 'Sustainably harvested from New Zealand forests. A thick, golden texture with complex earthy sweetness, each batch independently tested for methylglyoxal content.',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Waikato, New Zealand',
      altitude: 'Remote Leptospermum scoparium forests',
      harvest: 'Seasonal harvest, single-apiary batches',
    },
    macros: { fat: '0g', carbs: '82g', protein: '0.3g' },
    pairingIds: ['sourdough-bread', 'oat-milk', 'dark-chocolate'],
    logistics: {
      freshness: '24-month shelf life',
      packaging: 'UV-filtered glass jar, tamper-evident seal',
      carbon: '1.2kg CO₂e per unit (air freight)',
    },
  },
  {
    id: 'olive-oil',
    label: 'EXTRA VIRGIN',
    name: 'Olive Oil',
    size: '17OZ',
    price: 22.00,
    category: 'pantry',
    description: 'First cold-press oil from early-season Koroneiki olives. Vibrant green with a fresh, peppery finish from 400-year-old trees, pressed within 4 hours of picking.',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Kalamata, Peloponnese',
      altitude: 'Mediterranean hillside groves',
      harvest: 'November harvest, hand-raked',
    },
    macros: { fat: '100g', carbs: '0g', protein: '0g' },
    pairingIds: ['sourdough-bread', 'mixed-tomatoes', 'sharp-cheddar'],
    logistics: {
      freshness: '18-month shelf life from press date',
      packaging: 'Dark glass bottle, nitrogen-sealed',
      carbon: '0.7kg CO₂e per unit',
    },
  },
  {
    id: 'almond-butter',
    label: 'STONE-GROUND',
    name: 'Almond Butter',
    size: '12OZ',
    price: 14.00,
    category: 'pantry',
    description: 'Single-ingredient almond butter made from dry-roasted California almonds. Stone-ground in small batches for a naturally creamy texture with no added oils.',
    image: 'https://images.unsplash.com/photo-1612187209234-a5a5e2e4f26f?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Central Valley, California',
      altitude: 'San Joaquin Valley, irrigated orchards',
      harvest: 'Late-summer shake harvest, solar-dried',
    },
    macros: { fat: '56g', carbs: '19g', protein: '21g' },
    pairingIds: ['sourdough-bread', 'medjool-dates', 'fuji-apples'],
    logistics: {
      freshness: '6-month shelf life',
      packaging: 'Glass jar, steel lid, recyclable',
      carbon: '0.5kg CO₂e per unit',
    },
  },
  {
    id: 'tahini',
    label: 'STONE-GROUND',
    name: 'Tahini',
    size: '10OZ',
    price: 11.00,
    category: 'pantry',
    description: 'Silky-smooth sesame paste from Humera white sesame seeds. Slow-roasted and stone-milled to a pourable consistency with a deeply nutty, bitter-sweet flavor.',
    image: 'https://images.unsplash.com/photo-1585238341710-4d3ff484184d?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Humera, Ethiopia',
      altitude: 'Semi-arid highland, 1,400m elevation',
      harvest: 'Hand-harvested, sun-dried on racks',
    },
    macros: { fat: '53g', carbs: '21g', protein: '17g' },
    pairingIds: ['medjool-dates', 'sourdough-bread', 'lacinato-kale'],
    logistics: {
      freshness: '12-month shelf life',
      packaging: 'Glass jar, tamper-evident seal',
      carbon: '0.4kg CO₂e per unit',
    },
  },
  {
    id: 'garlic-confit',
    label: 'HOUSE-MADE',
    name: 'Garlic Confit',
    size: '8OZ',
    price: 10.00,
    category: 'pantry',
    description: 'Whole garlic cloves slow-poached in olive oil until meltingly tender. Spreadable on bread or mashed into sauces for instant depth and sweetness.',
    image: 'https://images.unsplash.com/photo-1501420193726-1f65acd36070?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Gilroy, California',
      altitude: 'Coastal valley, alluvial soil',
      harvest: 'Summer harvest, cured 3 weeks before confiting',
    },
    macros: { fat: '22g', carbs: '8g', protein: '1.5g' },
    pairingIds: ['sourdough-bread', 'olive-focaccia', 'rainbow-chard'],
    logistics: {
      freshness: '4 weeks refrigerated',
      packaging: 'Glass jar, olive-oil submerged',
      carbon: '0.2kg CO₂e per unit',
    },
  },
  {
    id: 'lemon-vinaigrette',
    label: 'HOUSE-MADE',
    name: 'Meyer Lemon Vinaigrette',
    size: '8OZ',
    price: 8.50,
    category: 'pantry',
    description: 'Bright and herbaceous dressing made with fresh Meyer lemons, Dijon, shallots, and extra virgin olive oil. Shaken daily in small batches.',
    image: 'https://images.unsplash.com/photo-1541014741259-de529411b96a?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Ojai, California',
      altitude: 'Inland valley, citrus microclimate',
      harvest: 'Seasonal Meyer lemons, hand-juiced',
    },
    macros: { fat: '18g', carbs: '3g', protein: '0g' },
    pairingIds: ['lacinato-kale', 'rainbow-chard', 'mixed-tomatoes'],
    logistics: {
      freshness: '14 days refrigerated',
      packaging: 'Glass bottle, recyclable cap',
      carbon: '0.15kg CO₂e per unit',
    },
  },
  {
    id: 'san-marzano-tomatoes',
    label: 'DOP',
    name: 'San Marzano Tomatoes',
    size: '28OZ',
    price: 7.50,
    category: 'pantry',
    description: 'Certified DOP whole peeled tomatoes from the Sarno Valley. Sweet, low-acid flesh with minimal seeds, packed in their own juice within hours of harvest.',
    image: 'https://images.unsplash.com/photo-1597362925123-77861d3fbac7?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Sarno Valley, Campania',
      altitude: 'Volcanic soil beneath Mount Vesuvius',
      harvest: 'Hand-picked August–September at peak ripeness',
    },
    macros: { fat: '0.2g', carbs: '4g', protein: '1g' },
    pairingIds: ['olive-oil', 'garlic-confit', 'olive-focaccia'],
    logistics: {
      freshness: '36-month shelf life',
      packaging: 'BPA-free lined tin, recyclable',
      carbon: '0.5kg CO₂e per unit',
    },
  },
  {
    id: 'wildflower-honey',
    label: 'RAW',
    name: 'Wildflower Honey',
    size: '12OZ',
    price: 12.00,
    category: 'pantry',
    description: 'Unfiltered, raw honey from rooftop apiaries surrounded by wildflower meadows. Complex floral notes shift with each seasonal harvest.',
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Hudson Valley, New York',
      altitude: 'Rolling meadows, 200m elevation',
      harvest: 'Seasonal extraction, never heated above hive temperature',
    },
    macros: { fat: '0g', carbs: '82g', protein: '0.3g' },
    pairingIds: ['sourdough-bread', 'coconut-yogurt', 'morning-scones'],
    logistics: {
      freshness: '24-month shelf life',
      packaging: 'Hexagonal glass jar, cork-lined lid',
      carbon: '0.1kg CO₂e per unit',
    },
  },

  // ─── DAIRY-ALT (7) ─────────────────────────────────────────────
  {
    id: 'oat-milk',
    label: 'BARISTA',
    name: 'Oat Milk',
    size: '32OZ',
    price: 6.00,
    category: 'dairy-alt',
    description: 'A smooth, creamy blend designed for coffee. Naturally sweetened by the grain, with a silky texture that holds micro-foam perfectly.',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Swedish Lapland',
      altitude: 'Northern latitude slow-growth oats',
      harvest: 'Milled within 48 hours of harvest',
    },
    macros: { fat: '1.5g', carbs: '7g', protein: '1g' },
    pairingIds: ['green-juice', 'sourdough-bread', 'manuka-honey'],
    logistics: {
      freshness: '14 days refrigerated',
      packaging: 'Tetra Pak, FSC-certified',
      carbon: '0.4kg CO₂e per unit',
    },
  },
  {
    id: 'coconut-yogurt',
    label: 'PROBIOTIC',
    name: 'Coconut Yogurt',
    size: '16OZ',
    price: 8.00,
    category: 'dairy-alt',
    description: 'Thick, tangy cultured coconut cream with six live probiotic strains. Unsweetened with a rich, spoonable body that rivals traditional Greek yogurt.',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Ben Tre Province, Vietnam',
      altitude: 'Mekong Delta coconut groves',
      harvest: 'Young coconuts, cold-separated cream',
    },
    macros: { fat: '14g', carbs: '6g', protein: '1g' },
    pairingIds: ['fresh-blueberries', 'manuka-honey', 'medjool-dates'],
    logistics: {
      freshness: '21 days refrigerated',
      packaging: 'Glass jar, silicone lid, reusable',
      carbon: '0.5kg CO₂e per unit',
    },
  },
  {
    id: 'cashew-cream-cheese',
    label: 'CULTURED',
    name: 'Cashew Cream Cheese',
    size: '8OZ',
    price: 9.00,
    category: 'dairy-alt',
    description: 'Fermented cashew spread with a tangy, cream cheese flavor. Made with rejuvelac culture for authentic tang and a smooth, spreadable consistency.',
    image: 'https://images.unsplash.com/photo-1559561853-08451507cbe7?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Ivory Coast & in-house fermentation',
      altitude: 'Tropical cashew orchards',
      harvest: 'Raw cashews, 48-hour fermentation cycle',
    },
    macros: { fat: '22g', carbs: '8g', protein: '5g' },
    pairingIds: ['everything-bagels', 'seeded-crackers', 'mixed-tomatoes'],
    logistics: {
      freshness: '14 days refrigerated',
      packaging: 'Recyclable PP tub, paper label',
      carbon: '0.3kg CO₂e per unit',
    },
  },
  {
    id: 'almond-milk',
    label: 'UNSWEETENED',
    name: 'Almond Milk',
    size: '32OZ',
    price: 5.50,
    category: 'dairy-alt',
    description: 'Clean, light almond milk made with sprouted almonds and filtered water. No gums, no fillers, just a delicate nutty sweetness.',
    image: 'https://images.unsplash.com/photo-1600788886242-5c96aabe3757?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Modesto, California',
      altitude: 'Central Valley almond orchards',
      harvest: 'Sprouted 12 hours, cold-blended, strained',
    },
    macros: { fat: '2.5g', carbs: '1g', protein: '1g' },
    pairingIds: ['cold-brew-concentrate', 'multigrain-loaf', 'fresh-blueberries'],
    logistics: {
      freshness: '10 days refrigerated',
      packaging: 'Glass bottle, deposit return program',
      carbon: '0.3kg CO₂e per unit',
    },
  },
  {
    id: 'hemp-milk',
    label: 'ORGANIC',
    name: 'Hemp Milk',
    size: '32OZ',
    price: 6.50,
    category: 'dairy-alt',
    description: 'Earthy, creamy hemp seed milk rich in omega-3 fatty acids. A subtle nutty flavor that works beautifully in smoothies and baking.',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Manitoba, Canada',
      altitude: 'Prairie farmland, rich black soil',
      harvest: 'Fall harvest, cold-pressed hulled seeds',
    },
    macros: { fat: '3g', carbs: '1g', protein: '3g' },
    pairingIds: ['berry-smoothie', 'multigrain-loaf', 'medjool-dates'],
    logistics: {
      freshness: '12 days refrigerated',
      packaging: 'Tetra Pak, FSC-certified',
      carbon: '0.25kg CO₂e per unit',
    },
  },
  {
    id: 'macadamia-milk',
    label: 'BARISTA',
    name: 'Macadamia Milk',
    size: '32OZ',
    price: 7.50,
    category: 'dairy-alt',
    description: 'Ultra-creamy macadamia nut milk with natural richness that froths beautifully. The highest-fat plant milk for an indulgent, full-bodied mouthfeel.',
    image: 'https://images.unsplash.com/photo-1517448931760-9bf4414148c5?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Big Island, Hawaii',
      altitude: '400m elevation, volcanic soil',
      harvest: 'Gravity-harvested, sun-dried, cold-pressed',
    },
    macros: { fat: '5g', carbs: '1g', protein: '0.5g' },
    pairingIds: ['cold-brew-concentrate', 'matcha-latte', 'pain-au-chocolat'],
    logistics: {
      freshness: '10 days refrigerated',
      packaging: 'Glass bottle, aluminum cap',
      carbon: '0.6kg CO₂e per unit',
    },
  },
  {
    id: 'oat-creamer',
    label: 'VANILLA',
    name: 'Oat Creamer',
    size: '16OZ',
    price: 5.00,
    category: 'dairy-alt',
    description: 'A rich, vanilla-infused oat creamer for coffee and tea. Made with real vanilla bean and a touch of coconut cream for extra body.',
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Vermont, USA',
      altitude: 'New England oat farms',
      harvest: 'Madagascar vanilla beans, Nordic oats',
    },
    macros: { fat: '3g', carbs: '5g', protein: '0g' },
    pairingIds: ['cold-brew-concentrate', 'matcha-latte', 'golden-milk-latte'],
    logistics: {
      freshness: '14 days refrigerated',
      packaging: 'Recyclable carton, plant-based liner',
      carbon: '0.2kg CO₂e per unit',
    },
  },

  // ─── SWEET TREATS (7) ──────────────────────────────────────────
  {
    id: 'dark-chocolate',
    label: 'SEA SALT',
    name: 'Dark Chocolate',
    size: '3OZ',
    price: 7.00,
    category: 'sweet-treats',
    description: '72% cacao sourced from single-estate farms, topped with hand-harvested salt crystals. Stone-ground for 72 hours to develop extraordinary depth.',
    image: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Esmeraldas, Ecuador',
      altitude: 'Lowland tropical, Nacional varietal',
      harvest: 'Beans fermented on-site for 6 days',
    },
    macros: { fat: '42g', carbs: '46g', protein: '8g' },
    pairingIds: ['manuka-honey', 'sharp-cheddar', 'olive-oil'],
    logistics: {
      freshness: '12-month shelf life',
      packaging: 'Foil-wrapped, recycled card sleeve',
      carbon: '0.6kg CO₂e per unit',
    },
  },
  {
    id: 'pistachio-halva',
    label: 'ARTISAN',
    name: 'Pistachio Halva',
    size: '8OZ',
    price: 12.00,
    category: 'sweet-treats',
    description: 'Ethereally light tahini confection swirled with roasted Bronte pistachios. Hand-pulled for a delicate, flaky texture that dissolves on the tongue.',
    image: 'https://images.unsplash.com/photo-1579954115567-dff2b6193a4f?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Istanbul, Turkey',
      altitude: 'Traditional copper-kettle production',
      harvest: 'Bronte pistachios, Ethiopian sesame',
    },
    macros: { fat: '28g', carbs: '40g', protein: '12g' },
    pairingIds: ['tahini', 'dark-chocolate', 'cold-brew-concentrate'],
    logistics: {
      freshness: '3-month shelf life',
      packaging: 'Wax paper, tin box',
      carbon: '0.5kg CO₂e per unit',
    },
  },
  {
    id: 'salted-caramels',
    label: 'SMALL BATCH',
    name: 'Salted Caramels',
    size: '6PK',
    price: 9.00,
    category: 'sweet-treats',
    description: 'Buttery, hand-cut caramels finished with Maldon sea salt flakes. Cooked to a precise 248°F for the perfect balance of chew and melt.',
    image: 'https://images.unsplash.com/photo-1548907040-4bea42c25755?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Portland, Oregon',
      altitude: 'Small-batch copper pot production',
      harvest: 'Grass-fed butter, Maldon salt, Madagascar vanilla',
    },
    macros: { fat: '8g', carbs: '22g', protein: '1g' },
    pairingIds: ['dark-chocolate', 'cold-brew-concentrate', 'fuji-apples'],
    logistics: {
      freshness: '6-week shelf life',
      packaging: 'Wax paper wraps, recycled card box',
      carbon: '0.2kg CO₂e per unit',
    },
  },
  {
    id: 'coconut-macaroons',
    label: 'GLUTEN-FREE',
    name: 'Coconut Macaroons',
    size: '6PK',
    price: 8.00,
    category: 'sweet-treats',
    description: 'Toasted on the outside, soft and chewy within. Made with shredded coconut, egg whites, and a dark chocolate base for a naturally gluten-free indulgence.',
    image: 'https://images.unsplash.com/photo-1558326567-98ae2405596b?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Coconut from Sri Lanka, chocolate from Ghana',
      altitude: 'Coastal coconut groves, tropical cacao farms',
      harvest: 'Dried coconut flakes, single-origin couverture',
    },
    macros: { fat: '12g', carbs: '24g', protein: '2g' },
    pairingIds: ['oat-milk', 'cold-brew-concentrate', 'macadamia-milk'],
    logistics: {
      freshness: '10 days at room temperature',
      packaging: 'Compostable box, tissue paper',
      carbon: '0.3kg CO₂e per unit',
    },
  },
  {
    id: 'rose-turkish-delight',
    label: 'ARTISAN',
    name: 'Rose Turkish Delight',
    size: '6OZ',
    price: 10.00,
    category: 'sweet-treats',
    description: 'Fragrant, pillowy lokum perfumed with Isparta rosewater and studded with pistachios. Dusted in a cloud of powdered sugar and cornstarch.',
    image: 'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Isparta, Turkey',
      altitude: 'Rose Valley, 1,000m elevation',
      harvest: 'Damask roses, hand-picked at dawn in May',
    },
    macros: { fat: '3g', carbs: '36g', protein: '2g' },
    pairingIds: ['pistachio-halva', 'matcha-latte', 'manuka-honey'],
    logistics: {
      freshness: '4-month shelf life',
      packaging: 'Wooden gift box, parchment-lined',
      carbon: '0.4kg CO₂e per unit',
    },
  },
  {
    id: 'maple-pecan-granola',
    label: 'SMALL BATCH',
    name: 'Maple Pecan Granola',
    size: '12OZ',
    price: 11.00,
    category: 'sweet-treats',
    description: 'Chunky clusters of oats, pecans, and pumpkin seeds slow-baked with Grade A dark maple syrup. Lightly spiced with cinnamon and a pinch of sea salt.',
    image: 'https://images.unsplash.com/photo-1517456793572-1d8efd6dc135?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Vermont, USA',
      altitude: 'Sugarhouse maple, 400m elevation',
      harvest: 'Late-winter maple tap, Georgia pecans',
    },
    macros: { fat: '16g', carbs: '48g', protein: '8g' },
    pairingIds: ['coconut-yogurt', 'oat-milk', 'fresh-blueberries'],
    logistics: {
      freshness: '3-month shelf life',
      packaging: 'Resealable kraft bag, compostable',
      carbon: '0.2kg CO₂e per unit',
    },
  },
  {
    id: 'matcha-mochi',
    label: 'HANDMADE',
    name: 'Matcha Mochi',
    size: '6PK',
    price: 9.50,
    category: 'sweet-treats',
    description: 'Chewy rice flour mochi filled with matcha-infused sweet red bean paste. Each piece is hand-formed and dusted with kinako roasted soybean powder.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Kyoto, Japan',
      altitude: 'Traditional wagashi workshop',
      harvest: 'Uji matcha, Hokkaido azuki beans',
    },
    macros: { fat: '1g', carbs: '28g', protein: '3g' },
    pairingIds: ['matcha-latte', 'manuka-honey', 'dark-chocolate'],
    logistics: {
      freshness: '5 days refrigerated',
      packaging: 'Bamboo tray, compostable film',
      carbon: '0.6kg CO₂e per unit',
    },
  },

  // ─── DELI (7) ──────────────────────────────────────────────────
  {
    id: 'sharp-cheddar',
    label: 'AGED',
    name: 'Sharp Cheddar',
    size: '8OZ',
    price: 11.00,
    category: 'deli',
    description: 'Grass-fed white cheddar aged for 12 months. A firm, crumbly texture with a bold savory bite and tyrosine crystals that signal proper aging.',
    image: 'https://images.unsplash.com/photo-1618164436241-4473940d1f5c?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Somerset, England',
      altitude: 'Rolling lowland pastures',
      harvest: 'Raw milk from 200-head Friesian herd, hand-turned daily',
    },
    macros: { fat: '33g', carbs: '1.3g', protein: '25g' },
    pairingIds: ['sourdough-bread', 'dark-chocolate', 'olive-oil'],
    logistics: {
      freshness: '60 days refrigerated after cutting',
      packaging: 'Wax-coated paper, vacuum-sealed',
      carbon: '0.9kg CO₂e per unit',
    },
  },
  {
    id: 'smoked-salmon',
    label: 'WILD-CAUGHT',
    name: 'Smoked Salmon',
    size: '4OZ',
    price: 14.00,
    category: 'deli',
    description: 'Cold-smoked wild sockeye over alder wood for 12 hours. Silky, translucent slices with a delicate smoke that never overpowers the clean oceanic flavor.',
    image: 'https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Bristol Bay, Alaska',
      altitude: 'Cold North Pacific waters',
      harvest: 'Summer gillnet season, bled and iced on boat',
    },
    macros: { fat: '4g', carbs: '0g', protein: '20g' },
    pairingIds: ['everything-bagels', 'cashew-cream-cheese', 'lemon-vinaigrette'],
    logistics: {
      freshness: '21 days vacuum-sealed',
      packaging: 'Vacuum-sealed recyclable film',
      carbon: '0.8kg CO₂e per unit',
    },
  },
  {
    id: 'gruyere-wedge',
    label: 'CAVE-AGED',
    name: 'Gruyère Wedge',
    size: '6OZ',
    price: 13.00,
    category: 'deli',
    description: 'Swiss alpine cheese aged 12 months in limestone caves. Rich, nutty, and slightly sweet with those characteristic tiny crystalline pockets throughout.',
    image: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Fribourg, Switzerland',
      altitude: '1,100m alpine pastures',
      harvest: 'Summer milk from Simmental cows, copper vat production',
    },
    macros: { fat: '32g', carbs: '0.4g', protein: '27g' },
    pairingIds: ['sourdough-bread', 'olive-focaccia', 'fuji-apples'],
    logistics: {
      freshness: '45 days refrigerated after cutting',
      packaging: 'Cheese paper, wax-sealed',
      carbon: '1.0kg CO₂e per unit',
    },
  },
  {
    id: 'prosciutto-di-parma',
    label: 'DOP',
    name: 'Prosciutto di Parma',
    size: '3OZ',
    price: 12.00,
    category: 'deli',
    description: 'Hand-sliced, 18-month aged prosciutto from heritage breed pigs. Paper-thin slices with a sweet, nutty depth and a melt-on-the-tongue fat cap.',
    image: 'https://images.unsplash.com/photo-1551730459-92db2a308d6a?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Langhirano, Parma',
      altitude: 'Apennine foothill curing houses',
      harvest: 'Heritage Large White pigs, sea salt only',
    },
    macros: { fat: '18g', carbs: '0g', protein: '26g' },
    pairingIds: ['olive-focaccia', 'gruyere-wedge', 'medjool-dates'],
    logistics: {
      freshness: '30 days vacuum-sealed',
      packaging: 'Interleaved parchment, vacuum-sealed',
      carbon: '1.1kg CO₂e per unit',
    },
  },
  {
    id: 'marinated-olives',
    label: 'HOUSE-MADE',
    name: 'Marinated Olives',
    size: '8OZ',
    price: 7.50,
    category: 'deli',
    description: 'A trio of Castelvetrano, Kalamata, and Cerignola olives marinated in herbs, citrus zest, and chili flake. Briny, buttery, and endlessly snackable.',
    image: 'https://images.unsplash.com/photo-1563065145-47e8f53d1e94?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Sicily, Greece & Puglia',
      altitude: 'Mediterranean coastal groves',
      harvest: 'Fall harvest, brine-cured 3–6 months',
    },
    macros: { fat: '15g', carbs: '4g', protein: '1g' },
    pairingIds: ['sharp-cheddar', 'olive-focaccia', 'prosciutto-di-parma'],
    logistics: {
      freshness: '30 days refrigerated',
      packaging: 'Glass deli jar, reusable',
      carbon: '0.3kg CO₂e per unit',
    },
  },
  {
    id: 'chicken-liver-mousse',
    label: 'HOUSE-MADE',
    name: 'Chicken Liver Mousse',
    size: '6OZ',
    price: 10.00,
    category: 'deli',
    description: 'Silky, whipped mousse made from pasture-raised chicken livers, cognac, and herbs. Finished with a thin layer of clarified butter for preservation.',
    image: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Sonoma County, California',
      altitude: 'Pasture-raised poultry farms',
      harvest: 'Heritage breed chickens, free-range',
    },
    macros: { fat: '24g', carbs: '2g', protein: '14g' },
    pairingIds: ['sourdough-bread', 'seeded-crackers', 'marinated-olives'],
    logistics: {
      freshness: '10 days refrigerated',
      packaging: 'Ceramic ramekin, beeswax lid',
      carbon: '0.4kg CO₂e per unit',
    },
  },
  {
    id: 'burrata',
    label: 'FRESH',
    name: 'Burrata',
    size: '8OZ',
    price: 12.00,
    category: 'deli',
    description: 'A pillow of hand-pulled mozzarella filled with cream and stracciatella. When cut, the center spills out in a luscious, milky cascade.',
    image: 'https://images.unsplash.com/photo-1626957341926-98752fc2ba90?auto=format&fit=crop&w=800&q=80',
    origin: {
      region: 'Puglia, Italy',
      altitude: 'Murgia plateau, limestone-filtered water',
      harvest: 'Made daily from morning milk delivery',
    },
    macros: { fat: '20g', carbs: '1g', protein: '12g' },
    pairingIds: ['mixed-tomatoes', 'olive-oil', 'olive-focaccia'],
    logistics: {
      freshness: '3 days from production',
      packaging: 'Water-sealed compostable tub',
      carbon: '0.7kg CO₂e per unit',
    },
  },
];

export const collections = {
  'daily-fresh': {
    name: 'Daily Fresh',
    tagline: 'The good stuff, picked today.',
    categories: ['produce', 'bakery', 'deli'] as const,
  },
  'the-pantry': {
    name: 'The Pantry',
    tagline: 'Staples worth stocking up on.',
    categories: ['pantry', 'dairy-alt', 'sweet-treats'] as const,
  },
  'morning-rituals': {
    name: 'Morning Rituals',
    tagline: 'Start your day the right way.',
    categories: ['juice-bar'] as const,
  },
} as const;

export function getProduct(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getPairings(product: Product): Product[] {
  // Start with explicit pairings
  const explicit = product.pairingIds
    .map((id) => products.find((p) => p.id === id))
    .filter((p): p is Product => p !== undefined);

  // Fill remaining slots with same-category items
  const sameCat = products
    .filter((p) => p.category === product.category && p.id !== product.id && !product.pairingIds.includes(p.id));

  return [...explicit, ...sameCat].slice(0, 6);
}
