export interface NutritionMacros {
  fat: string;
  carbs: string;
  protein: string;
}

export interface Product {
  id: string;
  label: string;
  name: string;
  size: string;
  price: number;
  category: 'produce' | 'dairy-alt' | 'bakery' | 'juice-bar' | 'pantry' | 'sweet-treats' | 'deli';
  description: string;
  image: string;
  origin: {
    region: string;
    altitude: string;
    harvest: string;
  };
  macros: NutritionMacros;
  pairingIds: string[];
  logistics: {
    freshness: string;
    packaging: string;
    carbon: string;
  };
}

export const products: Product[] = [
  // ─── THE GARDEN / PRODUCE (10) ────────────────────────────────
  {
    id: 'organic-kale',
    label: 'ORGANIC',
    name: 'Organic Kale',
    size: '1 BUNCH',
    price: 3.50,
    category: 'produce',
    description: 'Hand-picked lacinato kale grown in the cool marine fog of Salinas Valley. Each dark, blue-green leaf is selected for deep pigment and structural integrity — a sign of high chlorophyll and mineral density. The flat, dinosaur-style leaves hold dressings beautifully and become silky when massaged with olive oil and lemon. Rich in vitamins A, K, and C, with a mildly sweet, earthy flavour that mellows further when sautéed or roasted.',
    image: '/assets/garden1.webp',
    origin: { region: 'Salinas Valley, CA', altitude: 'Coastal lowland, cool marine fog', harvest: 'Hand-cut at dawn for maximum turgor' },
    macros: { fat: '0.5g', carbs: '6g', protein: '3g' },
    pairingIds: ['olive-oil', 'meyer-lemon', 'sea-salt'],
    logistics: { freshness: '3–5 days from harvest', packaging: 'Compostable band wrap', carbon: '0.3kg CO₂e per unit' },
  },
  {
    id: 'heirloom-tomato',
    label: 'HEIRLOOM',
    name: 'Heirloom Tomato',
    size: '1 LB',
    price: 4.00,
    category: 'produce',
    description: 'Grown from heritage seeds passed down through generations of Central Coast farmers, these heirloom tomatoes deliver a complex balance of bright acidity and natural sugars that modern hybrids simply cannot replicate. Each fruit is vine-ripened and hand-selected for its unique colour — deep burgundy, golden yellow, or striped green — and its tender, juice-heavy flesh. Dry-farmed without irrigation to concentrate flavour, they are at their absolute best sliced thick with sea salt and a drizzle of quality olive oil.',
    image: '/assets/garden2.webp',
    origin: { region: 'Central Coast, CA', altitude: 'Mediterranean climate, dry-farmed', harvest: 'Vine-ripened, hand-selected' },
    macros: { fat: '0.2g', carbs: '4g', protein: '1g' },
    pairingIds: ['sea-salt', 'olive-oil', 'fresh-mint'],
    logistics: { freshness: '4–6 days from harvest', packaging: 'Recycled pulp tray', carbon: '0.4kg CO₂e per unit' },
  },
  {
    id: 'hass-avocado',
    label: 'ORGANIC',
    name: 'Hass Avocado',
    size: 'EACH',
    price: 2.50,
    category: 'produce',
    description: 'Sourced from the volcanic highlands of Michoacán at over 2,200 metres elevation, these Hass avocados develop an exceptionally buttery texture and rich, nutty flavour thanks to the mineral-dense soil and cool mountain air. Each fruit is hand-picked at peak maturity and arrives with a creamy, pale-green interior that yields perfectly to a spoon. With 15g of heart-healthy monounsaturated fat per fruit, it is as nourishing as it is indulgent — ideal on sourdough, in guacamole, or simply halved with a squeeze of Meyer lemon and flaky salt.',
    image: '/assets/garden3.webp',
    origin: { region: 'Michoacán, Mexico', altitude: '2,200m elevation, volcanic soil', harvest: 'Hand-picked at peak ripeness' },
    macros: { fat: '15g', carbs: '9g', protein: '2g' },
    pairingIds: ['sea-salt', 'meyer-lemon', 'sourdough-boule'],
    logistics: { freshness: '5–7 days from harvest', packaging: 'Recycled kraft tray', carbon: '0.8kg CO₂e per unit' },
  },
  {
    id: 'pink-lady-apple',
    label: 'CONVENTIONAL',
    name: 'Red Apple',
    size: 'EACH',
    price: 1.50,
    category: 'produce',
    description: 'A late-season apple harvested from sun-drenched orchards in Washington\'s Yakima Valley, prized for its satisfying crunch and perfectly balanced sweet-tart profile. The crisp, dense flesh snaps cleanly with every bite, releasing a burst of juice with subtle honey and vanilla undertones. Excellent eaten out of hand, sliced into salads, or paired with sharp cheese and raw honey for a simple, elegant snack.',
    image: '/assets/garden4.webp',
    origin: { region: 'Yakima Valley, WA', altitude: 'Temperate orchard, full sun exposure', harvest: 'Late-season harvest for maximum sweetness' },
    macros: { fat: '0.2g', carbs: '25g', protein: '0.5g' },
    pairingIds: ['raw-honey', 'almond-croissant'],
    logistics: { freshness: '2–3 weeks cold storage', packaging: 'Loose, no packaging', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'blueberry',
    label: 'WILD',
    name: 'Blueberry',
    size: '6 OZ',
    price: 5.00,
    category: 'produce',
    description: 'Wild lowbush blueberries hand-raked from the acidic barrens of coastal Maine, where harsh winters and short growing seasons produce berries that are smaller, more intensely pigmented, and dramatically more flavourful than their cultivated cousins. Each 6-ounce clamshell is packed with anthocyanins and antioxidants — nearly twice the concentration of farmed varieties. The flavour is deep, almost wine-like, with a tart edge that pairs beautifully with cultured cashew yogurt, raw honey, or folded into morning granola.',
    image: '/assets/garden5.webp',
    origin: { region: 'Maine, USA', altitude: 'Wild lowbush, acidic barrens', harvest: 'Hand-raked at peak ripeness' },
    macros: { fat: '0.3g', carbs: '14g', protein: '0.7g' },
    pairingIds: ['cashew-yogurt', 'raw-honey'],
    logistics: { freshness: '5–7 days from harvest', packaging: 'Compostable clamshell', carbon: '0.3kg CO₂e per unit' },
  },
  {
    id: 'meyer-lemon',
    label: 'ORGANIC',
    name: 'Meyer Lemon',
    size: 'EACH',
    price: 1.25,
    category: 'produce',
    description: 'A natural cross between a citron and a mandarin orange, the Meyer lemon is prized for its thin, fragrant skin and juice that is sweeter and more floral than a conventional lemon. Grown in the subtropical microclimate of Ojai, California, each fruit is tree-ripened until the rind turns a deep golden-orange. The aromatic zest is loaded with essential oils, making it exceptional in vinaigrettes, baked goods, cocktails, and simple warm-water tonics. A kitchen staple that elevates everything it touches.',
    image: '/assets/garden6.webp',
    origin: { region: 'Ojai, CA', altitude: 'Coastal valley, subtropical microclimate', harvest: 'Tree-ripened, hand-picked' },
    macros: { fat: '0.3g', carbs: '9g', protein: '1g' },
    pairingIds: ['raw-honey', 'earl-grey-tea', 'vitality-juice'],
    logistics: { freshness: '7–10 days from harvest', packaging: 'Loose, no packaging', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'fresh-mint',
    label: 'ORGANIC',
    name: 'Fresh Mint',
    size: '1 BUNCH',
    price: 2.00,
    category: 'produce',
    description: 'Grown in the rich alluvial soil of Hudson Valley, New York, this spearmint is cut to order at peak oil content so it arrives intensely aromatic and vibrant. The broad, deeply veined leaves release a cool, sweet menthol fragrance when bruised — ideal for muddling into cocktails, steeping as a digestive tea, blending into tonic waters, or scattering over spring salads and grain bowls. Each bunch is wrapped in a compostable band and stays fresh for up to five days when stored stems-down in water.',
    image: '/assets/garden7.webp',
    origin: { region: 'Hudson Valley, NY', altitude: 'River valley, rich alluvial soil', harvest: 'Cut-to-order for peak oil content' },
    macros: { fat: '0.1g', carbs: '1g', protein: '0.4g' },
    pairingIds: ['meyer-lemon', 'matcha-tonic'],
    logistics: { freshness: '3–5 days from harvest', packaging: 'Compostable band wrap', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'english-cucumber',
    label: 'HOTHOUSE',
    name: 'English Cucumber',
    size: 'EACH',
    price: 2.00,
    category: 'produce',
    description: 'Hydroponically grown in controlled-environment greenhouses in British Columbia, this English cucumber is seedless, thin-skinned, and remarkably crisp. Its mild, clean flavour and high water content — over 96% — make it one of the most refreshing vegetables you can eat. Harvested daily at the optimal 12-inch length, it requires no peeling and delivers a satisfying crunch whether sliced into salads, layered in sandwiches, infused into water, or simply eaten with a pinch of flaky sea salt and fresh mint.',
    image: '/assets/garden8.webp',
    origin: { region: 'British Columbia, Canada', altitude: 'Controlled environment, hydroponic', harvest: 'Daily harvest at optimal length' },
    macros: { fat: '0.1g', carbs: '4g', protein: '0.7g' },
    pairingIds: ['sea-salt', 'fresh-mint'],
    logistics: { freshness: '7–10 days', packaging: 'Shrink-wrapped for freshness', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'rainbow-carrot',
    label: 'HERITAGE',
    name: 'Rainbow Carrot',
    size: '1 LB',
    price: 4.50,
    category: 'produce',
    description: 'Heritage-variety carrots hand-pulled from the mineral-rich glacial loam of Skagit Valley, Washington. Each bunch contains a spectrum of colours — deep purple, golden yellow, crimson red, and classic orange — each with its own distinct flavour profile, from sweet and mild to peppery and earthy. Delivered with soil still clinging to the roots for maximum freshness. Stunning roasted whole with olive oil and honey, shaved raw into salads, or slow-braised as a side for roasted meats.',
    image: '/assets/garden9.webp',
    origin: { region: 'Skagit Valley, WA', altitude: 'Glacial river delta, mineral-rich loam', harvest: 'Hand-pulled, soil-on for freshness' },
    macros: { fat: '0.2g', carbs: '10g', protein: '0.9g' },
    pairingIds: ['olive-oil', 'raw-honey', 'sea-salt'],
    logistics: { freshness: '10–14 days cold storage', packaging: 'Recycled kraft bag', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'arugula',
    label: 'WILD',
    name: 'Arugula',
    size: '5 OZ',
    price: 4.00,
    category: 'produce',
    description: 'Wild-harvested from the sun-drenched hillside terraces of Tuscany, this arugula delivers an assertive peppery bite and a slightly nutty, mustard-like complexity that farmed varieties rarely achieve. The young leaves are harvested at peak spice — small, tender, and intensely green — before they turn bitter. A cornerstone of Italian cuisine, it transforms a simple salad into something memorable when tossed with shaved Parmigiano, aged balsamic, and a generous pour of first-press olive oil.',
    image: '/assets/garden10.webp',
    origin: { region: 'Tuscany, Italy', altitude: 'Sun-drenched hillside terraces', harvest: 'Young leaf harvest for peak spice' },
    macros: { fat: '0.3g', carbs: '2g', protein: '2.6g' },
    pairingIds: ['olive-oil', 'balsamic', 'prosciutto'],
    logistics: { freshness: '3–5 days from harvest', packaging: 'Compostable clamshell', carbon: '0.4kg CO₂e per unit' },
  },

  // ─── THE BAKERY (11) ─────────────────────────────────────────
  {
    id: 'sourdough-boule',
    label: 'ARTISAN',
    name: 'Sourdough Boule',
    size: '1 LOAF',
    price: 9.00,
    category: 'bakery',
    description: 'Our signature boule begins with a 30-year-old sourdough starter and undergoes a full 24-hour cold fermentation that develops a complex, lactic tang and a deeply blistered, scorched crust. Baked on a stone deck at 500°F with steam injection, the interior is open-crumbed and chewy with a slight sweetness that balances the sour. Each loaf is shaped by hand at 4am and is best enjoyed the same day — torn, not sliced — with olive oil, aged cheese, or simply on its own.',
    image: '/assets/bakery1.webp',
    origin: { region: 'In-house Bakery', altitude: 'Stone-deck oven, 500°F', harvest: 'Baked daily at 4am' },
    macros: { fat: '1g', carbs: '36g', protein: '6g' },
    pairingIds: ['olive-oil', 'prosciutto', 'manchego'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper sleeve', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'plain-croissant',
    label: 'FRENCH',
    name: 'Plain Croissant',
    size: 'EACH',
    price: 4.00,
    category: 'bakery',
    description: 'A three-day labour of love: 81 precisely folded layers of French cultured butter and high-protein flour, laminated by hand to create the shattering, golden exterior and soft, honeycomb interior that define a true Parisian croissant. Each one is proof-retarded overnight for flavour depth, then baked until the edges caramelise and the butter between the layers creates delicate, audible flakes. Best enjoyed warm from the oven alongside a strong espresso or a drizzle of raw wildflower honey.',
    image: '/assets/bakery2.webp',
    origin: { region: 'In-house Bakery', altitude: 'Laminated over 3 days', harvest: 'Baked fresh every morning' },
    macros: { fat: '14g', carbs: '26g', protein: '4g' },
    pairingIds: ['ethiopian-beans', 'raw-honey'],
    logistics: { freshness: 'Same-day bake', packaging: 'Wax paper sleeve', carbon: '0.15kg CO₂e per unit' },
  },
  {
    id: 'baguette',
    label: 'ARTISAN',
    name: 'Baguette',
    size: 'EACH',
    price: 4.50,
    category: 'bakery',
    description: 'A classic Parisian-style baguette with a paper-thin, shatteringly crisp crust and a soft, airy interior with an irregular, open crumb structure. Made with just four ingredients — flour, water, salt, and wild yeast — and baked twice daily in a steam-injected stone oven to achieve that signature crackle. The flavour is subtly wheaty with a mild tang from natural fermentation. Perfect as a vehicle for cheese and charcuterie, or simply torn and dipped in olive oil at the dinner table.',
    image: '/assets/bakery3.webp',
    origin: { region: 'In-house Bakery', altitude: 'Steam-injected stone oven', harvest: 'Baked twice daily' },
    macros: { fat: '1g', carbs: '33g', protein: '5g' },
    pairingIds: ['olive-oil', 'manchego', 'prosciutto'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper bag', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'pain-au-chocolat',
    label: 'FRENCH',
    name: 'Pain au Chocolat',
    size: 'EACH',
    price: 5.00,
    category: 'bakery',
    description: 'The same meticulous laminated dough as our croissant, rolled around two batons of Valrhona Guanaja 70% dark chocolate couverture. As the pastry bakes, the chocolate softens into a molten, bittersweet core that contrasts with the buttery, flaky layers surrounding it. Each pain au chocolat is baked fresh every morning and arrives with a glossy egg-wash sheen and deeply caramelised edges. An indulgent breakfast or afternoon treat, especially alongside a cold brew or oat latte.',
    image: '/assets/bakery4.webp',
    origin: { region: 'In-house Bakery', altitude: 'Valrhona Guanaja 70% couverture', harvest: 'Baked fresh every morning' },
    macros: { fat: '16g', carbs: '30g', protein: '5g' },
    pairingIds: ['cold-brew', 'oat-latte'],
    logistics: { freshness: 'Same-day bake', packaging: 'Wax paper sleeve', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'rye-bread',
    label: 'HERITAGE',
    name: 'Rye Bread',
    size: '1 LOAF',
    price: 8.50,
    category: 'bakery',
    description: 'A dense, deeply flavoured loaf made from stone-milled heritage rye flour and studded with whole caraway seeds that release a warm, anise-like aroma as you slice. The long fermentation develops a malty sweetness and a tight, moist crumb that stays fresh longer than wheat breads. Each loaf is hearty enough to stand up to bold toppings — smoked fish, sharp mustard, aged cheese — and makes exceptional toast that crisps on the outside while staying chewy within.',
    image: '/assets/bakery5.webp',
    origin: { region: 'In-house Bakery', altitude: 'Heritage rye flour, stone-milled', harvest: 'Baked daily' },
    macros: { fat: '1g', carbs: '34g', protein: '5g' },
    pairingIds: ['prosciutto', 'manchego', 'green-olives'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper sleeve', carbon: '0.15kg CO₂e per unit' },
  },
  {
    id: 'brioche-bun',
    label: 'ENRICHED',
    name: 'Brioche Bun',
    size: 'EACH',
    price: 2.00,
    category: 'bakery',
    description: 'An enriched dough made with free-range eggs and European-style cultured butter, yielding a bun that is impossibly soft, pillowy, and slightly sweet. Glazed with egg wash before baking to achieve a deep golden-brown crown with a gentle sheen. The tender crumb pulls apart in soft, cotton-like layers. Versatile enough for a breakfast sandwich, a gourmet burger, or simply split and spread with vegan butter and a thin layer of raw honey.',
    image: '/assets/bakery6.webp',
    origin: { region: 'In-house Bakery', altitude: 'Free-range eggs, cultured butter', harvest: 'Baked fresh every morning' },
    macros: { fat: '10g', carbs: '28g', protein: '5g' },
    pairingIds: ['raw-honey', 'vegan-butter'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper bag', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'focaccia-slice',
    label: 'ARTISAN',
    name: 'Focaccia Slice',
    size: 'EACH',
    price: 5.00,
    category: 'bakery',
    description: 'A generous slab of hand-dimpled focaccia generously infused with cold-pressed Ligurian olive oil and finished with Maldon sea salt flakes that crunch against the pillowy, oil-rich crumb. The dough undergoes a slow, overnight rise that develops deep flavour and an airy, open texture with crisp, golden edges. Each slice is baked daily and arrives still fragrant from the oven. Serve alongside a bowl of soup, layer with arugula and heirloom tomato, or tear off pieces for dipping.',
    image: '/assets/bakery7.webp',
    origin: { region: 'In-house Bakery', altitude: 'Ligurian EVOO, Maldon flakes', harvest: 'Baked daily' },
    macros: { fat: '8g', carbs: '30g', protein: '4g' },
    pairingIds: ['olive-oil', 'arugula', 'heirloom-tomato'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper wrap', carbon: '0.15kg CO₂e per unit' },
  },
  {
    id: 'ciabatta',
    label: 'ARTISAN',
    name: 'Ciabatta',
    size: 'EACH',
    price: 6.00,
    category: 'bakery',
    description: 'An Italian classic made from an exceptionally high-hydration dough (80%) that produces a remarkably light, open crumb with large, irregular air pockets — the signature honeycomb structure that ciabatta is known for. The thin, flour-dusted crust gives way to a soft, chewy interior with a mild, wheaty sweetness. Baked twice daily for peak freshness. Ideal sliced horizontally for panini, served alongside a charcuterie board, or simply torn and dipped in first-press olive oil.',
    image: '/assets/bakery8.webp',
    origin: { region: 'In-house Bakery', altitude: '80% hydration, slow ferment', harvest: 'Baked twice daily' },
    macros: { fat: '1g', carbs: '32g', protein: '5g' },
    pairingIds: ['olive-oil', 'prosciutto'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper bag', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'almond-croissant',
    label: 'FRENCH',
    name: 'Almond Croissant',
    size: 'EACH',
    price: 6.00,
    category: 'bakery',
    description: 'A day-old croissant given a second life: split open, filled with a generous layer of rum-infused frangipane made from ground Sicilian almonds, then baked again until the exterior crisps and the cream sets into a rich, marzipan-like filling. Topped with toasted almond slivers and a dusting of powdered sugar. The result is a pastry that is simultaneously crunchy, chewy, and custardy — more decadent than the original croissant and absolutely extraordinary alongside an oat latte or espresso.',
    image: '/assets/bakery9.webp',
    origin: { region: 'In-house Bakery', altitude: 'Sicilian almonds, dark rum', harvest: 'Baked fresh every morning' },
    macros: { fat: '18g', carbs: '32g', protein: '6g' },
    pairingIds: ['oat-latte', 'ethiopian-beans'],
    logistics: { freshness: 'Same-day bake', packaging: 'Wax paper sleeve', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'multigrain-loaf',
    label: 'HERITAGE',
    name: 'Multigrain Loaf',
    size: '1 LOAF',
    price: 8.00,
    category: 'bakery',
    description: 'A nutrient-dense loaf packed with a blend of ancient grains — spelt, millet, and quinoa — along with golden flax seeds and toasted sunflower seeds that add crunch and nuttiness to every slice. The dough is slow-fermented to develop a complex, slightly sweet flavour and a moist, hearty crumb that holds up well for sandwiches and toast. High in fibre and plant protein, this is the everyday loaf for anyone who wants substance and flavour in equal measure.',
    image: '/assets/bakery10.webp',
    origin: { region: 'In-house Bakery', altitude: 'Spelt, millet, quinoa, flax blend', harvest: 'Baked daily' },
    macros: { fat: '3g', carbs: '28g', protein: '7g' },
    pairingIds: ['raw-honey', 'vegan-butter', 'hass-avocado'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper sleeve', carbon: '0.15kg CO₂e per unit' },
  },
  {
    id: 'olive-rosemary-loaf',
    label: 'ARTISAN',
    name: 'Olive Rosemary Loaf',
    size: '1 LOAF',
    price: 9.50,
    category: 'bakery',
    description: 'A savoury artisan loaf stone-baked with halved Taggiasca olives from Liguria and sprigs of wild rosemary folded directly into the dough. The olives release their briny, buttery oil during baking, creating pockets of intense flavour throughout the crumb, while the rosemary perfumes every slice with its piney, Mediterranean warmth. The crust is thick and crackly, the interior soft and aromatic. Outstanding on its own, with a glass of wine, or sliced alongside a cheese and olive board.',
    image: '/assets/bakery11.webp',
    origin: { region: 'In-house Bakery', altitude: 'Taggiasca olives, wild rosemary', harvest: 'Baked daily' },
    macros: { fat: '5g', carbs: '30g', protein: '5g' },
    pairingIds: ['olive-oil', 'manchego', 'arugula'],
    logistics: { freshness: 'Same-day bake', packaging: 'Paper sleeve', carbon: '0.15kg CO₂e per unit' },
  },

  // ─── SUSHI / DELI (5) ────────────────────────────────────────
  {
    id: 'salmon-nigiri',
    label: 'SUSHI',
    name: 'Salmon Nigiri',
    size: '4 PC',
    price: 14.00,
    category: 'deli',
    description: 'Wild-caught King Salmon from the cold Pacific waters of Alaska, sustainably line-caught and processed using the Japanese ike jime technique for unparalleled freshness and texture. Each piece of silky, coral-orange fish is draped over a compact pillow of hand-pressed Koshihikari rice seasoned with house-blended vinegar. The fat marbling melts on the tongue, delivering a clean, oceanic sweetness. Served same-day with freshly grated wasabi and pickled ginger.',
    image: '/assets/sushi1.webp',
    origin: { region: 'Alaska, USA', altitude: 'Wild-caught, cold Pacific waters', harvest: 'Line-caught, ike jime processed' },
    macros: { fat: '8g', carbs: '20g', protein: '14g' },
    pairingIds: ['wasabi-root', 'maki-roll'],
    logistics: { freshness: 'Same-day preparation', packaging: 'Recycled PET tray', carbon: '1.2kg CO₂e per unit' },
  },
  {
    id: 'tuna-sashimi',
    label: 'SUSHI',
    name: 'Tuna Sashimi',
    size: '6 PC',
    price: 18.00,
    category: 'deli',
    description: 'Grade-1 sashimi-quality lean Bluefin tuna (akami) sourced through Tsukiji Market in Tokyo. Each ruby-red slice is cut against the grain with a single stroke of a yanagiba knife to preserve the clean, silky texture and delicate iron-rich flavour. Flash-frozen at sea to -60°C and thawed precisely before slicing, ensuring parasitic safety without compromising the buttery mouthfeel. Served with soy, wasabi, and shiso — an exercise in purity and restraint.',
    image: '/assets/sushi2.webp',
    origin: { region: 'Tsukiji Market, Japan', altitude: 'Deep-sea caught, flash-frozen', harvest: 'Grade-1 sashimi quality' },
    macros: { fat: '1g', carbs: '0g', protein: '26g' },
    pairingIds: ['wasabi-root', 'yellowtail-nigiri'],
    logistics: { freshness: 'Same-day sliced', packaging: 'Temperature-controlled tray', carbon: '2.0kg CO₂e per unit' },
  },
  {
    id: 'yellowtail-nigiri',
    label: 'SUSHI',
    name: 'Yellowtail Nigiri',
    size: '4 PC',
    price: 16.00,
    category: 'deli',
    description: 'Premium Hamachi (Japanese yellowtail) from sustainably managed open-water pens off Kyushu, hand-filleted daily by our in-house sushi team. The pale pink flesh is remarkably buttery with a clean, slightly sweet finish and a delicate fat content that melts at body temperature. Each piece is pressed onto seasoned rice with a whisper of freshly grated wasabi and a micro-drop of yuzu citrus. One of the most elegant and approachable pieces in our nigiri selection.',
    image: '/assets/sushi3.webp',
    origin: { region: 'Kyushu, Japan', altitude: 'Sustainably farmed, open-water pens', harvest: 'Hand-filleted daily' },
    macros: { fat: '6g', carbs: '18g', protein: '12g' },
    pairingIds: ['salmon-nigiri', 'wasabi-root'],
    logistics: { freshness: 'Same-day preparation', packaging: 'Recycled PET tray', carbon: '1.5kg CO₂e per unit' },
  },
  {
    id: 'maki-roll',
    label: 'SUSHI',
    name: 'Maki Roll',
    size: '8 PC',
    price: 12.00,
    category: 'deli',
    description: 'A hand-rolled maki made with premium Ariake Sea nori that is toasted to order for maximum crispness and umami depth. Choose from seasonal vegetable or fish fillings, each paired with perfectly seasoned Koshihikari rice. The rolls are cut with a wet blade for clean, precise edges and served within minutes of preparation. The nori wrapper provides a satisfying snap, giving way to the soft, flavourful interior — a testament to the beauty of simplicity in Japanese cuisine.',
    image: '/assets/sushi4.webp',
    origin: { region: 'In-house Sushi Bar', altitude: 'Hand-rolled to order', harvest: 'Ariake Sea nori sheets' },
    macros: { fat: '3g', carbs: '28g', protein: '8g' },
    pairingIds: ['salmon-nigiri', 'matcha-tonic'],
    logistics: { freshness: 'Same-day preparation', packaging: 'Recycled PET tray', carbon: '0.8kg CO₂e per unit' },
  },
  {
    id: 'wasabi-root',
    label: 'PREMIUM',
    name: 'Wasabi Root',
    size: 'EACH',
    price: 25.00,
    category: 'deli',
    description: 'Authentic wasabi japonica rhizome grown in the mountain spring-fed beds of Shizuoka Prefecture over an 18-month cultivation cycle — not the horseradish-based imitation found in most restaurants. When freshly grated on a sharkskin oroshi, it releases a clean, floral heat that rises through the sinuses and dissipates quickly, leaving a subtle sweetness. The flavour is complex, almost herbaceous, and transforms sashimi and nigiri into an entirely different experience. Store wrapped in damp paper and refrigerated.',
    image: '/assets/sushi5.webp',
    origin: { region: 'Shizuoka, Japan', altitude: 'Mountain spring-fed beds, shade-grown', harvest: '18-month cultivation cycle' },
    macros: { fat: '0.6g', carbs: '24g', protein: '5g' },
    pairingIds: ['salmon-nigiri', 'tuna-sashimi'],
    logistics: { freshness: '2 weeks refrigerated', packaging: 'Damp paper wrap', carbon: '1.0kg CO₂e per unit' },
  },

  // ─── TONIC BAR / JUICE BAR (5) ───────────────────────────────
  {
    id: 'vitality-juice',
    label: 'COLD-PRESSED',
    name: 'Vitality Juice',
    size: '16 OZ',
    price: 11.00,
    category: 'juice-bar',
    description: 'A vibrant, anti-inflammatory cold-pressed juice made from fresh turmeric root, raw ginger, and Meyer lemon — hydraulically pressed without heat to preserve every enzyme, vitamin, and volatile compound. The turmeric provides a warm, earthy backbone with powerful curcumin content, while the ginger adds a sharp, warming kick. The Meyer lemon brightens and balances with its floral acidity. Pressed fresh daily at 6am and bottled in returnable glass. Shake well — the good stuff settles.',
    image: '/assets/tonicbar1.webp',
    origin: { region: 'In-house Tonic Bar', altitude: 'Hydraulic cold-press, no heat', harvest: 'Pressed daily at 6am' },
    macros: { fat: '0.5g', carbs: '18g', protein: '1g' },
    pairingIds: ['immunity-shot', 'aloe-water'],
    logistics: { freshness: 'Same-day press', packaging: 'Glass bottle, returnable', carbon: '0.15kg CO₂e per unit' },
  },
  {
    id: 'matcha-tonic',
    label: 'CEREMONIAL',
    name: 'Matcha Tonic',
    size: '12 OZ',
    price: 8.00,
    category: 'juice-bar',
    description: 'Ceremonial-grade first-harvest matcha from Uji, Kyoto, stone-milled to a silky powder and whisked to order with chilled sparkling alkaline water. The result is a bright jade-green tonic with a creamy, umami-rich body, a gentle vegetal sweetness, and fine effervescence that lifts the flavour. The L-theanine provides calm, sustained focus without the jitters of coffee. Each serving uses a full 2g of matcha — twice what most cafes pour — for a genuinely ceremonial experience in a bottle.',
    image: '/assets/tonicbar2.webp',
    origin: { region: 'In-house Tonic Bar', altitude: 'Uji, Kyoto first-harvest matcha', harvest: 'Whisked to order' },
    macros: { fat: '0g', carbs: '4g', protein: '2g' },
    pairingIds: ['vitality-juice', 'aloe-water'],
    logistics: { freshness: 'Made to order', packaging: 'Glass bottle', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'immunity-shot',
    label: 'WELLNESS',
    name: 'Immunity Shot',
    size: '2 OZ',
    price: 5.00,
    category: 'juice-bar',
    description: 'A potent 2-ounce wellness shot combining concentrated Hawaiian ginger juice with Mediterranean oil of oregano — two of nature\'s most powerful anti-microbial, anti-inflammatory compounds in a single, bracing dose. The ginger hits first with an intense, fiery warmth, followed by the herbaceous depth of the oregano oil. Not for the faint of heart. Best taken first thing in the morning or at the first sign of a cold. Pressed fresh daily and dispensed in a small glass vial.',
    image: '/assets/tonicbar3.webp',
    origin: { region: 'In-house Tonic Bar', altitude: 'Hawaiian ginger, Mediterranean oregano', harvest: 'Pressed fresh daily' },
    macros: { fat: '0g', carbs: '3g', protein: '0g' },
    pairingIds: ['vitality-juice', 'meyer-lemon'],
    logistics: { freshness: 'Same-day press', packaging: 'Glass vial', carbon: '0.05kg CO₂e per unit' },
  },
  {
    id: 'charcoal-cleanse',
    label: 'DETOX',
    name: 'Charcoal Cleanse',
    size: '16 OZ',
    price: 9.00,
    category: 'juice-bar',
    description: 'A striking jet-black cleansing juice made with food-grade activated charcoal derived from coconut shells, blended with organic lemon juice and a touch of raw agave for balance. The charcoal binds to impurities in the digestive tract while the lemon provides a bright, citrusy counterpoint. The flavour is surprisingly clean and refreshing — mildly sweet, lightly tart, with an earthy undertone. A popular post-indulgence reset. Bottled in returnable glass and pressed fresh daily.',
    image: '/assets/tonicbar4.webp',
    origin: { region: 'In-house Tonic Bar', altitude: 'Coconut-shell activated charcoal', harvest: 'Blended fresh daily' },
    macros: { fat: '0g', carbs: '12g', protein: '0g' },
    pairingIds: ['aloe-water', 'vitality-juice'],
    logistics: { freshness: 'Same-day press', packaging: 'Glass bottle, returnable', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'aloe-water',
    label: 'HYDRATION',
    name: 'Aloe Water',
    size: '16 OZ',
    price: 7.00,
    category: 'juice-bar',
    description: 'A gentle, ultra-hydrating water made from the cold-extracted inner gel of organic aloe vera leaves. The clear, slightly viscous liquid has a mild, clean flavour with a subtle botanical sweetness — no added sugar, no artificial flavours. Aloe is renowned for its digestive-soothing properties and skin-supporting vitamins. Sip it on its own as a morning hydration ritual, mix it into smoothies, or combine it with the Vitality Juice for an enhanced tonic experience. Cold-extracted daily in returnable glass.',
    image: '/assets/tonicbar5.webp',
    origin: { region: 'In-house Tonic Bar', altitude: 'Organic inner-leaf aloe vera', harvest: 'Cold-extracted daily' },
    macros: { fat: '0g', carbs: '6g', protein: '0g' },
    pairingIds: ['vitality-juice', 'immunity-shot'],
    logistics: { freshness: 'Same-day extraction', packaging: 'Glass bottle, returnable', carbon: '0.1kg CO₂e per unit' },
  },

  // ─── CAFE / JUICE BAR (5) ────────────────────────────────────
  {
    id: 'ethiopian-beans',
    label: 'SINGLE ORIGIN',
    name: 'Ethiopian Beans',
    size: '12 OZ',
    price: 24.00,
    category: 'juice-bar',
    description: 'Single-origin beans from the misty highlands of Yirgacheffe, Ethiopia, grown at 1,900 metres elevation under natural shade canopy. Hand-picked at peak cherry ripeness and washed-processed to produce a cup with remarkable clarity: jasmine florals on the nose, bright Meyer lemon acidity in the mid-palate, and a clean, tea-like finish with hints of bergamot. Roasted in small batches within seven days of delivery and sealed in a valved kraft bag to preserve freshness. Best brewed as a pour-over or Aeropress.',
    image: '/assets/cafe1.webp',
    origin: { region: 'Yirgacheffe, Ethiopia', altitude: '1,900m elevation, shade-grown', harvest: 'Hand-picked cherries, washed process' },
    macros: { fat: '0g', carbs: '0g', protein: '0.3g' },
    pairingIds: ['plain-croissant', 'pain-au-chocolat'],
    logistics: { freshness: 'Roasted within 7 days', packaging: 'Resealable kraft bag with valve', carbon: '1.5kg CO₂e per unit' },
  },
  {
    id: 'ceremonial-matcha',
    label: 'CEREMONIAL',
    name: 'Ceremonial Matcha',
    size: '30G TIN',
    price: 35.00,
    category: 'juice-bar',
    description: 'The highest grade of matcha available: first-flush, spring-harvest leaves from Uji, Kyoto, shade-grown under traditional tana canopies for 21 days to maximise chlorophyll and L-theanine content. Stone-milled on a granite mortar at just 40g per hour to prevent heat degradation. The resulting powder is an electric jade green with a rich, creamy umami flavour, zero bitterness, and a natural sweetness that lingers. Sealed in a nitrogen-flushed tin within hours of milling. Whisk with 80°C water for a transcendent, meditative cup.',
    image: '/assets/cafe2.webp',
    origin: { region: 'Uji, Kyoto, Japan', altitude: 'Shade-grown 21 days, stone-milled', harvest: 'First flush, spring harvest only' },
    macros: { fat: '0.3g', carbs: '4g', protein: '3g' },
    pairingIds: ['oat-milk', 'almond-croissant'],
    logistics: { freshness: 'Milled within 30 days', packaging: 'Sealed tin, nitrogen-flushed', carbon: '0.8kg CO₂e per unit' },
  },
  {
    id: 'cold-brew',
    label: 'SLOW-STEEPED',
    name: 'Cold Brew',
    size: '16 OZ',
    price: 6.00,
    category: 'juice-bar',
    description: 'Our house cold brew is steeped for a full 12 hours using coarsely ground Colombian single-origin beans and filtered water at a precise 1:8 ratio. The extended cold extraction produces a concentrate that is remarkably smooth, naturally sweet, and 67% lower in acidity than hot-brewed coffee. The flavour profile is rich and chocolatey with notes of toasted almond and a clean, lingering finish. Brewed fresh daily and served straight over ice or cut with house-made oat milk for a creamy, indulgent pour.',
    image: '/assets/cafe3.webp',
    origin: { region: 'In-house Cafe', altitude: 'Colombian single-origin, coarse grind', harvest: 'Steeped 12 hours in cold water' },
    macros: { fat: '0g', carbs: '0g', protein: '0.5g' },
    pairingIds: ['oat-milk', 'pain-au-chocolat'],
    logistics: { freshness: 'Brewed daily', packaging: 'Glass bottle', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'oat-latte',
    label: 'HOUSE',
    name: 'Oat Latte',
    size: '12 OZ',
    price: 6.50,
    category: 'juice-bar',
    description: 'A double shot of our Ethiopian house blend pulled through a La Marzocca Linea and combined with house-made oat milk that is pressed daily from Scandinavian oats — no gums, no thickeners, no seed oils. The oat milk steams into a velvety microfoam with a natural sweetness that complements the espresso\'s bright acidity and chocolate undertones. Served in a ceramic cup for dine-in or a compostable vessel for takeaway. The signature drink of our cafe — simple, balanced, and deeply satisfying.',
    image: '/assets/cafe4.webp',
    origin: { region: 'In-house Cafe', altitude: 'Ethiopian blend, house-made oat milk', harvest: 'Pulled to order' },
    macros: { fat: '5g', carbs: '16g', protein: '3g' },
    pairingIds: ['almond-croissant', 'plain-croissant'],
    logistics: { freshness: 'Made to order', packaging: 'Ceramic cup / compostable to-go', carbon: '0.1kg CO₂e per unit' },
  },
  {
    id: 'earl-grey-tea',
    label: 'LOOSE LEAF',
    name: 'Earl Grey Tea',
    size: '2 OZ TIN',
    price: 5.00,
    category: 'juice-bar',
    description: 'A refined loose-leaf Earl Grey blending first-flush Darjeeling black tea — hand-plucked at 2,000 metres and sun-withered — with cold-pressed Calabrian bergamot oil. The Darjeeling base provides a muscatel complexity and light body, while the bergamot adds a citrusy, almost floral perfume that defines the classic Earl Grey experience. Sealed in a tin canister within 48 hours of drying to lock in the volatile essential oils. Best steeped at 95°C for 3–4 minutes with a spoonful of raw honey and a wedge of Meyer lemon.',
    image: '/assets/cafe5.webp',
    origin: { region: 'Darjeeling, India', altitude: '2,000m elevation, first flush', harvest: 'Hand-plucked, sun-withered' },
    macros: { fat: '0g', carbs: '0g', protein: '0g' },
    pairingIds: ['raw-honey', 'shortbread', 'meyer-lemon'],
    logistics: { freshness: 'Sealed within 48 hours of drying', packaging: 'Tin canister, resealable', carbon: '0.5kg CO₂e per unit' },
  },

  // ─── THE DELI (3) ────────────────────────────────────────────
  {
    id: 'prosciutto',
    label: 'DOP',
    name: 'Prosciutto',
    size: '4 OZ',
    price: 18.00,
    category: 'deli',
    description: 'Authentic Prosciutto di Parma with DOP certification, aged for a full 24 months in the cool Apennine mountain air of Emilia-Romagna. The slow curing transforms heritage-breed pork into something transcendent: paper-thin slices that are silky, rosy pink, and laced with threads of sweet, nutty fat that dissolves on the tongue. Each portion is sliced to order on a Berkel flywheel slicer for uniform, melt-in-your-mouth thinness. Extraordinary draped over melon, layered on focaccia, or enjoyed alone with a glass of Prosecco.',
    image: '/assets/deli1.webp',
    origin: { region: 'Parma, Italy', altitude: 'Apennine mountain air-cured', harvest: '24-month aging, hand-sliced' },
    macros: { fat: '8g', carbs: '0g', protein: '12g' },
    pairingIds: ['manchego', 'green-olives', 'baguette'],
    logistics: { freshness: 'Sliced to order', packaging: 'Vacuum-sealed parchment', carbon: '1.8kg CO₂e per unit' },
  },
  {
    id: 'manchego',
    label: 'AGED',
    name: 'Manchego',
    size: '6 OZ',
    price: 14.00,
    category: 'deli',
    description: "A firm, golden sheep's milk cheese from the windswept plains of La Mancha, Spain, made from raw Manchega sheep's milk and aged for six months in limestone caves. The ageing develops a complex flavour profile: buttery and nutty at first, with a piquant, slightly tangy finish that intensifies toward the rind. The texture is dense yet crumbly, studded with tiny crystalline pockets of concentrated flavour. Perfect on a cheese board with quince paste and green olives, shaved over salads, or paired with aged balsamic and raw honey.",
    image: '/assets/deli2.webp',
    origin: { region: 'La Mancha, Spain', altitude: 'Manchega sheep, raw milk', harvest: '6-month cave aging' },
    macros: { fat: '16g', carbs: '0.5g', protein: '12g' },
    pairingIds: ['prosciutto', 'green-olives', 'raw-honey'],
    logistics: { freshness: 'Cut to order', packaging: 'Wax paper wrap', carbon: '1.2kg CO₂e per unit' },
  },
  {
    id: 'green-olives',
    label: 'SICILIAN',
    name: 'Green Olives',
    size: '8 OZ',
    price: 9.00,
    category: 'deli',
    description: 'The famed Castelvetrano olive from southwestern Sicily — bright green, uncommonly large, and prized for its mild, buttery flavour and firm, meaty texture that sets it apart from all other table olives. Hand-picked from Mediterranean hillside groves and gently brine-cured to preserve their natural sweetness and vivid colour. These olives are remarkably low in bitterness, making them irresistible eaten straight from the jar, tossed into pasta, arranged on a charcuterie board alongside prosciutto and Manchego, or blended into a vibrant tapenade.',
    image: '/assets/deli3.webp',
    origin: { region: 'Castelvetrano, Sicily', altitude: 'Mediterranean hillside groves', harvest: 'Hand-picked, brine-cured' },
    macros: { fat: '10g', carbs: '3g', protein: '1g' },
    pairingIds: ['prosciutto', 'manchego', 'focaccia-slice'],
    logistics: { freshness: '6-month brine cure', packaging: 'Glass jar, reusable', carbon: '0.6kg CO₂e per unit' },
  },

  // ─── THE PANTRY (5) ──────────────────────────────────────────
  {
    id: 'olive-oil',
    label: 'EVOO',
    name: 'Olive Oil',
    size: '500 ML',
    price: 30.00,
    category: 'pantry',
    description: 'A first cold press extra virgin olive oil made exclusively from Coratina olives harvested in November from ancient groves in Puglia, Italy. Stone-milled within hours of picking and extracted at temperatures below 27°C to preserve the full spectrum of polyphenols, antioxidants, and volatile aromatics. The flavour is bold and peppery with a grassy, artichoke-like freshness and a clean, lingering finish that catches the back of the throat — a sign of high-quality oil. Bottled in UV-protective dark glass. Use generously as a finishing oil.',
    image: '/assets/pantry1.webp',
    origin: { region: 'Puglia, Italy', altitude: 'Coratina olives, stone-milled', harvest: 'First cold press, November harvest' },
    macros: { fat: '14g', carbs: '0g', protein: '0g' },
    pairingIds: ['sourdough-boule', 'sea-salt', 'baguette'],
    logistics: { freshness: 'Current harvest year', packaging: 'Dark glass bottle, UV-protected', carbon: '0.8kg CO₂e per unit' },
  },
  {
    id: 'sea-salt',
    label: 'FLAKE',
    name: 'Sea Salt',
    size: '250G',
    price: 8.00,
    category: 'pantry',
    description: 'The iconic pyramidal salt flakes from the Blackwater estuary in Maldon, Essex — hand-harvested from traditional evaporation pans using techniques unchanged since 1882. Each hollow, pyramid-shaped crystal delivers a clean, mineral salinity and a satisfying crunch that dissolves on the tongue. Far more nuanced than table salt, with no bitterness or chemical aftertaste. The definitive finishing salt for everything from a perfectly seared steak to dark chocolate, avocado toast, and caramel desserts. A pantry essential for any serious cook.',
    image: '/assets/pantry2.webp',
    origin: { region: 'Maldon, Essex, UK', altitude: 'Blackwater estuary evaporation pans', harvest: 'Hand-harvested, sun-dried' },
    macros: { fat: '0g', carbs: '0g', protein: '0g' },
    pairingIds: ['olive-oil', 'hass-avocado', 'dark-chocolate'],
    logistics: { freshness: 'Shelf-stable 2 years', packaging: 'Recycled cardboard box', carbon: '0.3kg CO₂e per unit' },
  },
  {
    id: 'raw-honey',
    label: 'RAW',
    name: 'Raw Honey',
    size: '12 OZ',
    price: 25.00,
    category: 'pantry',
    description: 'Raw, unfiltered wildflower honey from small-batch apiaries in the Hudson Valley, New York. Never heated above 95°F, preserving the full complement of live enzymes, bee pollen, and propolis that industrial honey processing destroys. The flavour shifts with the seasons — spring batches are light and floral, while autumn harvests are darker, richer, and more complex with notes of buckwheat and goldenrod. Crystallisation is natural and a sign of purity; gently warm the jar to re-liquify. Extraordinary drizzled over cheese, stirred into tea, or eaten by the spoonful.',
    image: '/assets/pantry3.webp',
    origin: { region: 'Hudson Valley, NY', altitude: 'Wildflower meadow apiaries', harvest: 'Cold-extracted, never heated above 95°F' },
    macros: { fat: '0g', carbs: '17g', protein: '0g' },
    pairingIds: ['plain-croissant', 'earl-grey-tea', 'manchego'],
    logistics: { freshness: 'Shelf-stable 2+ years', packaging: 'Glass jar, reusable', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'balsamic',
    label: 'AGED',
    name: 'Balsamic',
    size: '250 ML',
    price: 45.00,
    category: 'pantry',
    description: 'A DOP-certified Aceto Balsamico Tradizionale di Modena aged for 15 years through a progression of five different wood barrels — oak, chestnut, cherry, juniper, and mulberry — each contributing its own character to the final product. The result is a syrupy, mahogany-dark vinegar with extraordinary depth: sweet and tart in equal measure, with layers of dried fruit, caramel, and subtle smokiness. Use sparingly as a finishing condiment — a few drops transform strawberries, Parmigiano, grilled meats, and even vanilla gelato.',
    image: '/assets/pantry4.webp',
    origin: { region: 'Modena, Italy', altitude: 'DOP certified, Trebbiano grapes', harvest: '15-year barrel aging, 5 wood progression' },
    macros: { fat: '0g', carbs: '14g', protein: '0g' },
    pairingIds: ['arugula', 'manchego', 'heirloom-tomato'],
    logistics: { freshness: 'Shelf-stable indefinitely', packaging: 'Glass bottle, wax seal', carbon: '0.5kg CO₂e per unit' },
  },
  {
    id: 'dijon-mustard',
    label: 'FRENCH',
    name: 'Dijon Mustard',
    size: '7 OZ',
    price: 7.00,
    category: 'pantry',
    description: 'An authentic Dijon mustard made in the traditional French method from brown mustard seeds ground on a stone mill with verjuice (the juice of unripe grapes) rather than vinegar, producing a sharper, more refined heat than mass-produced versions. The texture is coarse and grainy with visible seed fragments, and the flavour is complex — pungent and nasal-clearing at first, then settling into a warm, tangy depth. Essential for vinaigrettes, sandwich spreads, glazes for roasted meats, and classic French sauces.',
    image: '/assets/pantry5.webp',
    origin: { region: 'Dijon, France', altitude: 'Brown mustard seed, verjuice base', harvest: 'Stone-ground in small batches' },
    macros: { fat: '3g', carbs: '1g', protein: '2g' },
    pairingIds: ['prosciutto', 'baguette'],
    logistics: { freshness: 'Shelf-stable 18 months', packaging: 'Glass jar', carbon: '0.3kg CO₂e per unit' },
  },

  // ─── DAIRY ALT (5) ───────────────────────────────────────────
  {
    id: 'oat-milk',
    label: 'HOUSE-MADE',
    name: 'Oat Milk',
    size: '32 OZ',
    price: 8.00,
    category: 'dairy-alt',
    description: 'House-made daily in our on-site dairy lab from Scandinavian whole oats that are soaked, blended, and triple-filtered for a clean, creamy result with absolutely zero gums, thickeners, seed oils, or stabilisers. The natural oat sugars provide a gentle sweetness that makes this milk exceptional in coffee — it steams into a velvety microfoam that holds latte art beautifully. Also wonderful in cereal, smoothies, or baking. Bottled in returnable glass with a 5-day refrigerated shelf life. Shake before pouring.',
    image: '/assets/dairyalt1.webp',
    origin: { region: 'In-house Dairy Lab', altitude: 'Scandinavian oats, triple-filtered', harvest: 'Pressed fresh daily' },
    macros: { fat: '5g', carbs: '16g', protein: '3g' },
    pairingIds: ['ethiopian-beans', 'cold-brew', 'ceremonial-matcha'],
    logistics: { freshness: '5 days refrigerated', packaging: 'Glass bottle, returnable', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'almond-milk',
    label: 'HOUSE-MADE',
    name: 'Almond Milk',
    size: '32 OZ',
    price: 8.00,
    category: 'dairy-alt',
    description: 'Made from cold-pressed Sicilian almonds at a 25% almond-to-water ratio — five times the concentration of most commercial brands — resulting in a genuinely rich, nutty milk with a creamy body that performs beautifully in both coffee and cooking. No added sugars, no carrageenan, no fillers. The flavour is clean and naturally sweet with a distinct almond character. Pressed fresh daily in our dairy lab and bottled in returnable glass. Exceptional in matcha lattes, poured over granola, or used in baking where a subtle nuttiness is desired.',
    image: '/assets/dairyalt2.webp',
    origin: { region: 'In-house Dairy Lab', altitude: 'Sicilian almonds, cold-pressed', harvest: 'Pressed fresh daily' },
    macros: { fat: '8g', carbs: '3g', protein: '4g' },
    pairingIds: ['ethiopian-beans', 'ceremonial-matcha'],
    logistics: { freshness: '5 days refrigerated', packaging: 'Glass bottle, returnable', carbon: '0.3kg CO₂e per unit' },
  },
  {
    id: 'cashew-yogurt',
    label: 'CULTURED',
    name: 'Cashew Yogurt',
    size: '16 OZ',
    price: 6.00,
    category: 'dairy-alt',
    description: 'A thick, tangy plant-based yogurt cultured from a Vietnamese cashew cream base with six active probiotic strains over a 48-hour fermentation cycle. The result is remarkably close to traditional dairy yogurt in both texture and flavour — creamy, slightly tart, and satisfyingly thick without any gums or thickeners. Each serving delivers billions of live cultures for gut health. Delicious on its own, topped with wild blueberries and raw honey, layered in parfaits, or used as a base for smoothie bowls and salad dressings.',
    image: '/assets/dairyalt3.webp',
    origin: { region: 'In-house Dairy Lab', altitude: 'Vietnamese cashews, 6 probiotic strains', harvest: '48-hour fermentation cycle' },
    macros: { fat: '10g', carbs: '8g', protein: '4g' },
    pairingIds: ['blueberry', 'raw-honey'],
    logistics: { freshness: '7 days refrigerated', packaging: 'Glass jar, returnable', carbon: '0.3kg CO₂e per unit' },
  },
  {
    id: 'vegan-butter',
    label: 'CULTURED',
    name: 'Vegan Butter',
    size: '8 OZ',
    price: 7.00,
    category: 'dairy-alt',
    description: 'A cultured plant-based butter churned in small batches from a blend of organic coconut oil, cashew cream, and live cultures — producing a spread with the tangy depth and creamy mouthfeel of traditional European cultured butter. It melts, browns, and bakes like dairy butter, making it a genuine all-purpose substitute rather than a compromise. The flavour is clean and rich with a subtle cultured tang. Comes in a compostable tub and stays spreadable straight from the fridge. Exceptional on warm sourdough or brioche.',
    image: '/assets/dairyalt4.webp',
    origin: { region: 'In-house Dairy Lab', altitude: 'Coconut oil, cashew cream, cultures', harvest: 'Churned in small batches' },
    macros: { fat: '11g', carbs: '0g', protein: '0g' },
    pairingIds: ['sourdough-boule', 'brioche-bun'],
    logistics: { freshness: '14 days refrigerated', packaging: 'Compostable tub', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'coconut-cream',
    label: 'ORGANIC',
    name: 'Coconut Cream',
    size: '13.5 OZ',
    price: 5.00,
    category: 'dairy-alt',
    description: 'A thick, luxuriously rich coconut cream made from the first cold-press extraction of organic Sri Lankan coconuts — yielding a fat content of over 22% that is perfect for whipping, cooking, and dessert-making. The flavour is pure and intensely coconutty without any metallic or processed notes. Whip it into a dairy-free cream topping, stir it into curries for body and richness, fold it into chocolate mousse, or use it as the fat base for homemade ice cream. BPA-free can with an 18-month shelf life.',
    image: '/assets/dairyalt5.webp',
    origin: { region: 'Sri Lanka', altitude: 'Organic coconut plantations', harvest: 'Cold-pressed, first extraction' },
    macros: { fat: '24g', carbs: '3g', protein: '2g' },
    pairingIds: ['dark-chocolate', 'matcha-tonic'],
    logistics: { freshness: 'Shelf-stable 18 months', packaging: 'BPA-free can', carbon: '0.4kg CO₂e per unit' },
  },

  // ─── SWEET TREATS (4) ────────────────────────────────────────
  {
    id: 'dark-chocolate',
    label: 'SINGLE ORIGIN',
    name: 'Dark Chocolate',
    size: '3.5 OZ',
    price: 9.00,
    category: 'sweet-treats',
    description: 'A 70% cacao bar crafted from single-origin Nacional cacao beans grown at 800 metres elevation in Piura, Peru — one of the rarest and most prized cacao varieties in the world. Each bean is hand-fermented on the estate for five days and slowly conched for 72 hours to develop extraordinary depth: dark fruit and dried cherry on the nose, a smooth cocoa body, and a long, tobacco-like finish with hints of leather and cedar. Tempered to a perfect snap and wrapped in recycled foil. A chocolate for contemplation, not casual snacking.',
    image: '/assets/sweet1.webp',
    origin: { region: 'Piura, Peru', altitude: '800m elevation, Nacional cacao', harvest: 'Single-estate, hand-fermented' },
    macros: { fat: '12g', carbs: '14g', protein: '2g' },
    pairingIds: ['sea-salt', 'cold-brew', 'coconut-cream'],
    logistics: { freshness: 'Shelf-stable 12 months', packaging: 'Recycled foil, paper sleeve', carbon: '0.5kg CO₂e per unit' },
  },
  {
    id: 'dark-truffle',
    label: 'RAW',
    name: 'Dark Truffle',
    size: '6 PC',
    price: 15.00,
    category: 'sweet-treats',
    description: 'Hand-rolled daily in our confectionery from a blend of raw Peruvian cacao powder and puréed Medjool dates, finished with a light coating of Maldon sea salt flakes. The truffles are dense, fudgy, and deeply chocolatey — satisfying a sweet craving with whole-food ingredients and zero refined sugar. The salt crystals on the exterior provide a crunchy contrast and amplify the cacao\'s natural bitterness into something almost savoury. Six pieces per box, presented in a recycled kraft box. Best enjoyed slightly chilled with a shot of cold brew.',
    image: '/assets/sweet2.webp',
    origin: { region: 'In-house Confectionery', altitude: 'Peruvian raw cacao, Medjool dates', harvest: 'Hand-rolled daily' },
    macros: { fat: '8g', carbs: '18g', protein: '2g' },
    pairingIds: ['dark-chocolate', 'cold-brew'],
    logistics: { freshness: '7 days refrigerated', packaging: 'Recycled kraft box', carbon: '0.2kg CO₂e per unit' },
  },
  {
    id: 'shortbread',
    label: 'SCOTTISH',
    name: 'Shortbread',
    size: '6 PC',
    price: 10.00,
    category: 'sweet-treats',
    description: 'Traditional Scottish-style shortbread baked in small batches using just three ingredients: French cultured butter, cane sugar, and stone-milled flour — plus a generous scraping of Tahitian vanilla bean. The result is a biscuit of extraordinary simplicity and richness: buttery, sandy-textured, and crumbly, with a golden edge that provides a gentle caramel note. Six generous pieces per tin, each one stamped and docked by hand. The perfect companion to a pot of Earl Grey tea, a glass of dessert wine, or simply a quiet afternoon.',
    image: '/assets/sweet3.webp',
    origin: { region: 'In-house Bakery', altitude: 'French butter, Tahitian vanilla', harvest: 'Baked in small batches' },
    macros: { fat: '10g', carbs: '16g', protein: '2g' },
    pairingIds: ['earl-grey-tea', 'raw-honey'],
    logistics: { freshness: '10 days in tin', packaging: 'Recycled tin', carbon: '0.15kg CO₂e per unit' },
  },
  {
    id: 'dried-mango',
    label: 'ORGANIC',
    name: 'Dried Mango',
    size: '4 OZ',
    price: 8.00,
    category: 'sweet-treats',
    description: 'Premium Carabao mangoes from Cebu, Philippines — widely considered the sweetest mango variety in the world — hand-sliced at peak ripeness and sun-dried for five days without any added sugar, sulfur dioxide, or preservatives. The slow, natural drying concentrates the mango\'s tropical sweetness into chewy, intensely flavoured strips with a vivid golden colour. Each piece delivers the pure essence of the fruit: honeyed, slightly tangy, and impossibly aromatic. A guilt-free snack on its own, or chop and fold into yogurt, granola, or trail mix.',
    image: '/assets/sweet4.webp',
    origin: { region: 'Cebu, Philippines', altitude: 'Carabao mango, sun-dried 5 days', harvest: 'Peak-season fruit, hand-sliced' },
    macros: { fat: '0g', carbs: '28g', protein: '1g' },
    pairingIds: ['cashew-yogurt', 'dark-chocolate'],
    logistics: { freshness: 'Shelf-stable 6 months', packaging: 'Compostable pouch', carbon: '0.4kg CO₂e per unit' },
  },
];

// ─── PAIRINGS HELPER ───────────────────────────────────────────
export function getPairings(product: Product): Product[] {
  const explicit = product.pairingIds
    .map((id) => products.find((p) => p.id === id))
    .filter((p): p is Product => !!p);

  if (explicit.length >= 6) return explicit.slice(0, 6);

  const sameCat = products.filter(
    (p) => p.category === product.category && p.id !== product.id && !product.pairingIds.includes(p.id)
  );

  return [...explicit, ...sameCat].slice(0, 6);
}
